In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv('Data\\laptop_price.csv',encoding='latin1')
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [3]:
df.drop(['laptop_ID'],axis=1,inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(28)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.isnull().sum()

Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [ ]:
for col in df.columns:
    print("\nColumn:", col)
    print(df[col].unique())

Column: Company
['Apple' 'HP' 'Acer' 'Asus' 'Dell' 'Lenovo' 'Chuwi' 'MSI' 'Microsoft'
 'Toshiba' 'Huawei' 'Xiaomi' 'Vero' 'Razer' 'Mediacom' 'Samsung' 'Google'
 'Fujitsu' 'LG']

Column: Product
['MacBook Pro' 'Macbook Air' '250 G6' 'Aspire 3' 'ZenBook UX430UN'
 'Swift 3' 'Inspiron 3567' 'MacBook 12"' 'IdeaPad 320-15IKB' 'XPS 13'
 'Vivobook E200HA' 'Legion Y520-15IKBN' '255 G6' 'Inspiron 5379'
 '15-BS101nv (i7-8550U/8GB/256GB/FHD/W10)' 'MacBook Air' 'Inspiron 5570'
 'Latitude 5590' 'ProBook 470' 'LapBook 15.6"'
 'E402WA-GA010T (E2-6110/2GB/32GB/W10)'
 '17-ak001nv (A6-9220/4GB/500GB/Radeon' 'IdeaPad 120S-14IAP'
 'Inspiron 5770' 'ProBook 450' 'X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux)'
 'Inspiron 7577' 'X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce'
 'Aspire A515-51G' 'Inspiron 7773' 'IdeaPad 320-15ISK' 'Rog Strix'
 'X751NV-TY001T (N4200/4GB/1TB/GeForce' 'Yoga Book' 'ProBook 430'
 'Inspiron 3576' '15-bs002nv (i3-6006U/4GB/128GB/FHD/W10)' 'VivoBook Max'
 'GS73VR 7RG' 'X541UA-DM1897 (i3-6006U/4GB/256GB/FHD/Linux)' 'Vostro 5471'
 'IdeaPad 520S-14IKB' 'UX410UA-GV350T (i5-8250U/8GB/256GB/FHD/W10)'
 'ZenBook Pro' 'Stream 14-AX040wm' 'V310-15ISK (i5-7200U/4GB/1TB/FHD/W10)'
 'FX753VE-GC093 (i7-7700HQ/12GB/1TB/GeForce' 'Surface Laptop'
 'Inspiron 5370' 'GL72M 7RDX' 'Aspire E5-475'
 'FX503VD-E4022T (i7-7700HQ/8GB/1TB/GeForce' 'IdeaPad 320-15IKBN'
 'Aspire A515-51G-32MX' 'ProBook 440' 'IdeaPad 320-15AST'
 'Pavilion 15-CK000nv' 'FX503VM-E4007T (i7-7700HQ/16GB/1TB'
 'FX550IK-DM018T (FX-9830P/8GB/1TB/Radeon' 'Aspire 5' 'Probook 430'
 'Zenbook UX430UA' 'Spin 5' 'X541UV-DM1439T (i3-7100U/6GB/256GB/GeForce'
 'Omen 15-ce007nv' '15-bs017nv (i7-7500U/8GB/256GB/Radeon'
 '15-bw000nv (E2-9000e/4GB/500GB/Radeon' 'Envy 13-ad009n'
 'Pavilion 14-BK001nv' 'Ideapad 310-15ISK'
 'UX430UQ-GV209R (i7-7500U/8GB/256GB/GeForce' 'GP62M 7REX' 'Thinkpad T470'
 'VivoBook S15' 'ThinkPad Yoga' 'Probook 440' 'Spectre x360'
 'Inspiron 7570' 'X705UV-BX074T (i3-6006U/4GB/1TB/GeForce' 'Spin 3'
 'GS63VR 7RG' 'Probook 470' 'E402WA-GA007T (E2-6110/4GB/64GB/W10'
 'Inspiron 5567' 'Aspire A515-51G-37JS'
 '15-BS078nr (i7-7500U/8GB/1TB/W10)' 'V110-15IAP (N3350/4GB/1TB/No'
 'FX753VD-GC086T (i5-7300HQ/8GB/1TB' 'Envy 13-AD007nv' 'ThinkPad E480'
 'Satellite Pro' 'ZenBook UX430UA' 'EliteBook Folio'
 'X541NA (N3350/4GB/1TB/FHD/W10)' 'GE72MVR 7RG' 'Aspire A315-51'
 'Inspiron 5577' 'Inspiron 7567' 'V110-15IKB (i5-7200U/4GB/128GB/W10)'
 'GE73VR 7RE' 'EliteBook 840' '15-BS103nv (i5-8250U/6GB/256GB/Radeon'
 'Yoga 520-14IKB' 'ZenBook Flip' 'Inspiron 5579'
 'X555BP-XX180T (A9-9420/4GB/1TB/Radeon' 'Aspire A517-51G'
 'Aspire A315-31' 'GE63VR 7RE' 'MateBook X'
 '17-bs001nv (i5-7200U/6GB/2TB/Radeon' 'GT80S 6QF-074US'
 'V310-15IKB (i5-7200U/8GB/1TB' 'Yoga 920-13IKB' 'Mi Notebook' 'XPS 15'
 'Swift 7' 'Thinkpad Yoga' 'K147 (N3350/4GB/32GB/FHD/W10)'
 'IdeaPad 320-17IKBR' 'Blade Pro' 'Omen 17-W295'
 'V110-15ISK (i5-6200U/4GB/128GB/W10)' 'Aspire E5-576G'
 'Legion Y720-15IKB' 'Precision 7520' 'Aspire 7' 'ROG GL703VD-GC028T'
 '15-bs018nq (i3-6006U/4GB/500GB/FHD/No' 'IdeaPad 320-17IKB'
 'Latitude 5490' 'Portege Z30-C-16L' 'Alienware 17'
 'Vivobook X541UV-DM1217T' 'K756UX-T4340T (i5-7200U/8GB/500GB' 'ZBook 15u'
 'Pro P2540UA-XO0198T' '15-rb013nv (E2-9000e/4GB/500GB/W10)' 'Vostro 5468'
 'Aspire R7' 'X555QG-DM242T (A10-9620P/4GB/1TB' 'ROG G703VI-E5062T'
 'Nitro AN515-51' 'VivoBook Pro' 'F756UX-T4201D (i7-7500U/8GB/128GB'
 'Yoga 910-13IKB' '15-bs015dx (i5-7200U/8GB/1TB/W10)' 'Rog G701VIK-BA060T'
 'ROG G752VSK-GC493T' 'X505BP-BR019T (A9-9420/4GB/1TB/Radeon'
 'Vostro 5370' '15-BW094nd (A6-9220/8GB/128GB/W10)' 'Envy 17-U275cl'
 'GT73EVR 7RE' 'Yoga 720-15IKB' 'Vostro 3568'
 'V330-15IKB (i7-8550U/8GB/256GB/FHD/W10)' 'ThinkPad X1'
 'IdeaPad 320-17ISK' 'Ideapad 320-15IKBN'
 'SP315-51 (i7-7500U/12GB/1TB/FHD/W10)' 'Thinkpad T570'
 'Chromebook C910-C2ST' 'FX753VD-GC071T (i7-7700HQ/8GB/1TB/GeForce'
 '17-BS037cl (i3-6006U/8GB/1TB/W10)'
 'V330-15IKB (i5-8250U/8GB/256GB/FHD/W10)' 'Aspire A715-71G'
 'Precision 7720' 'IdeaPad 310-15ABR' 'ZenBook UX530UQ-PRO' 'VivoBook S14'
 'Rog GL702VS-GC095T' 'GL553VE-FY082T (i7-7700HQ/8GB/1TB'
 'IdeaPad 320-15IAP' 'EliteBook x360' 'IdeaPad 720S-13IKB' 'GE63VR 7RF'
 'ES1-523-84K7 (A8-7410/8GB/256GB/FHD/W10)' 'VivoBook Flip' 'ThinkPad 13'
 'ProBook 640' 'TravelMate B' 'Elitebook 840' 'ZenBook UX410UA-GV183T'
 'Aspire E5-575' 'Elitebook 820' 'GL72M 7REX'
 'UX510UX-CN269T (i7-7500U/8GB/256GB'
 'V310-15ISK (i3-6006U/4GB/1TB/FHD/W10)'
 'FX553VD-FY647T (i7-7700HQ/8GB/256GB/GeForce' 'Elitebook 850'
 'X541NA (N3350/4GB/1TB/Linux)' 'Inspiron 3552' 'IdeaPad 320-15ABR'
 'Stream 14-AX001nv' 'GP72MVR 7RFX' 'Zbook 15' 'Tecra A50-C-21G'
 'Latitude 7480' 'Zenbook UX410UA-GV027T' '15-AY023na (N3710/8GB/2TB/W10)'
 'Elitebook 1040' 'IdeaPad 110-17ACL'
 '15-bw003nv (A9-Series-9420/4GB/256GB/FHD/W10)' 'Yoga 11e'
 'VivoBook E403NA' 'Omen 17-w212nv'
 'V310-15ISK (i3-6006U/4GB/128GB/FHD/No' 'ROG Strix' 'IdeaPad 720S-14IKB'
 'Zenbook Flip' 'Thinkpad X1' 'Ideapad 510S-13IKB' 'Precision 3510'
 'Precision 5520' 'Rog GL753VD-GC042T' 'Rog GL753VE-GC070T'
 'Leopard GP72M' '15-BW004nv (A9-9420/4GB/256GB/Radeon' 'ThinkPad E580'
 'ThinkPad L470' 'Precision M5520' 'FX753VD-GC461T (i7-7700HQ/16GB/1TB'
 'GE73VR 7RF' 'Zenbook 3' 'Portege Z30-C-16P' 'Lenovo IdeaPad'
 'ThinkPad P51' 'Thinkpad T470p' '15-BS028nv (i3-6006U/4GB/1TB/Radeon'
 'Latitude 3380' 'EliteBook 1040' 'LapBook 12.3' 'ProBook 650'
 'X542UQ-DM117 (i3-7100U/8GB/1TB/GeForce' 'Latitude 5480' 'Omen 17-w207nv'
 'FlexBook Edge' 'Chromebook 3' 'Thinkpad 13' 'IdeaPad 320s-14IKB'
 'Thinkpad P51' '15-ra044nv (N3060/4GB/500GB/W10)' 'Pixelbook (Core'
 'ThinkPad T470s' 'ThinkPad X270' 'Omen 15-AX205na' 'Aspire ES1-572'
 'Precision 3520' 'GV62 7RD-1686NL' '15-bs024nv (i5-7200U/8GB/128GB/W10)'
 'ThinkPad T470' 'Inspiron 3168' '17-BS092ND (i3-6006U/8GB/256GB/W10)'
 'Pro P2540UA-AB51' 'IdeaPad 510s-14IKB'
 'X541NA-PD1003Y (N4200/4GB/500GB/W10)' 'Omen 17-an006nv' 'Thinkpad T460s'
 'Latitude 7390' 'Latitude E5470' 'Portege X30-D-10J' 'Lapbook 15,6'
 'ThinkPad E570' 'Thinkpad X270' 'Zenbook UX390UA' 'Thinkpad E570'
 'Portege X30-D-10L' 'Rog G752VL-UH71T' 'Thinkpad X260'
 'Ideapad 520-15IKBR' 'ThinkPad L570' 'VivoBook E201NA'
 '15-BS026nv (i5-7200U/8GB/256GB/Radeon' 'IdeaPad 320-14IAP'
 'Chromebook N23' 'ZenBook UX510UX-CN211T' 'Aspire A515-51G-59QF'
 'Envy 13-AB002nv' 'Vostro 5568' 'VivoBook E12'
 '15-bs190od (i5-8250U/4GB/1TB/W10)' 'ROG Zephyrus' 'Probook 450'
 'FX753VE-GC155T (i7-7700HQ/16GB/1TB' 'Spectre X360' 'Latitude 5580'
 'Zenbook UX510UW-FI095T' 'SmartBook Edge' 'Omen 15-ce006nv'
 'Thinkpad E470' 'Envy 13-AB020nr' 'VivoBook X540YA-XX519T'
 'ThinkPad E470' 'V310-15ISK (i5-6200U/4GB/1TB/FHD/No' 'ThinkPad T570'
 '17-X047na (i3-6006U/8GB/1TB/W10)' 'A541NA-GO342 (N3350/4GB/500GB/Linux)'
 'SmartBook 130' '15-bw007nv (A10-9620P/6GB/128GB/Radeon' 'Spin SP111-31'
 'V330-15IKB (i3-7130U/4GB/128GB/FHD/W10)' 'EliteBook 1030' 'Thinkpad P71'
 'FX553VD-DM627T (i5-7300HQ/8GB/1TB' 'Lifebook A557' 'ZBook 17'
 '14-am079na (N3710/8GB/2TB/W10)' '15-cd005nv (A9-9420/6GB/256GB/Radeon'
 'V330-15IKB (i5-8250U/4GB/500GB/FHD/W10)' 'SmartBook 141'
 'Tecra X40-D-10H' 'IdeaPad Y910-17ISK' 'GT73VR Titan' 'Chromebook 11'
 'GT80S 6QE' 'Omen 17-AN010nv' 'Ideapad 320-15IKBR'
 'TP501UA-CJ131T (i5-7200U/8GB/1TB/W10)' 'Inspiron 3179'
 'Notebook Odyssey' 'V320-17ISK (i3-6006U/4GB/500GB/FHD/No'
 'IdeaPad 110-15ISK' 'Latitude 5289' 'EliteBook 850' 'Aspire 1'
 'Laptop MSI' 'GS63VR 7RF' 'Tecra Z50-C-144' 'IdeaPad 310-15IKB'
 'Swift SF114-31-P5HY' 'Inspiron 7559' 'FX753VD-GC007T (i7-7700HQ/8GB/1TB'
 'GT62VR 7RE' 'CB5-132T-C9KK (N3160/4GB/32GB/Chrome' 'LifeBook A557'
 'SmartBook 140' 'Q304UA-BHI5T11 (i5-7200U/6GB/1TB/FHD/W10)' 'ZenBook 3'
 'V330-15IKB (i5-8250U/4GB/256GB/FHD/W10)' 'Ideapad 320-15ISK'
 'X541NA-GO414T (N3350/8GB/1TB/W10)' 'IdeaPad 100S-14IBR'
 '17-AK091ND (A9-9420/8GB/1TB/W10)' 'ROG GL553VE-FY022' 'Extensa EX2540'
 'Portege Z30-C-16J' 'ROG G701VI'
 'A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce' 'GL62M 7REX' 'Tecra A50-D-11M'
 'IdeaPad Y700-15ISK' 'Latitude E7470' 'Ideapad 320-15IAP'
 '15-ay047nv (i3-6006U/6GB/1TB/Radeon' 'GP72VR Leopard' 'Latitude 3580'
 '15-bs012nv (i7-7500U/8GB/1TB/Radeon' 'Tecra Z50-D-10E'
 'V310-15ISK (i5-7200U/8GB/1TB' 'Yoga 720-13IKB' 'Pavilion X360'
 'GP62 7RDX' 'Chromebook X360' 'Gram 15Z975' 'Aspire VX5-591G' 'GV62M 7RD'
 'L502NA-GO052T (N3350/4GB/128GB/W10)' 'Alienware 15' '17-bs000nv I3'
 'Yoga 730' '17-Y002nv (A10-9600P/6GB/2TB/Radeon'
 'V110-15ISK (3855U/4GB/500GB/W10)' 'Chromebook 14' 'IdeaPad 520s-14IKB'
 'TravelMate B117-M' 'Chromebook Flip' 'Portege Z30T-C-133'
 '15-bs011nv (i7-7500U/4GB/500GB/Radeon'
 'V310-15IKB (i5-7200U/4GB/1TB/FHD/W10)'
 'V310-15ISK (i3-6006U/4GB/500GB/No' 'ThinkPad P51s' 'Thinkpad T460p'
 '17-ak002nv (A10-9620P/6GB/2TB/Radeon'
 '110-15ACL (A6-7310/4GB/500GB/W10)' 'Smartbook 142'
 'V310-15IKB (i5-7200U/4GB/1TB/No' 'Inspiron 5378'
 '15-BW037na (A9-9420/4GB/1TB/Radeon' 'Predator 17'
 '15-BW091ND (A9-9420/6GB/1TB' 'Extensa EX2540-58KR'
 'V310-15IKB (i7-7500U/4GB/1TB/FHD/W10)' 'ZBook 15' 'Inspiron 7560'
 'Tecra X40-D-10G' 'Flex 5' 'Thinkpad P51s' 'Notebook 9' 'Zbook 17'
 'N23 (N3060/4GB/128GB/W10)' 'X550VX-XX015D (i5-6300HQ/4GB/1TB/GeForce'
 'Thinkpad T460' 'Pro P2540UA-XO0192R' 'Yoga 900-13ISK'
 '15-cb003na (i5-7300HQ/8GB/1TB' 'Latitude 7280' 'Zenbook UX330UA-AH5Q'
 'TravelMate P238-M' 'X751NV-TY001 (N4200/4GB/1TB/GeForce'
 'Tecra A40-C-1E5' 'EliteBook 820'
 'Q524UQ-BHI7T15 (i7-7500U/12GB/2TB/GeForce' 'Thinkpad P50' 'Vivobook Max'
 'Rog G752VS-BA171T' 'Tecra Z40-C-161' 'IdeaPad 110-15IBR' 'GS43VR 7RE'
 'GL62M (i5-7300HQ/8GB/1TB' 'Predator G9-793'
 'FX502VM-DM560T (i7-7700HQ/8GB/1TB' 'K146 (N3350/4GB/32GB/W10)'
 'Yoga 510-15IKB' 'R417NA-RS01 (N3350/4GB/32GB/W10)' 'Pro P2540UA-XS51'
 'Latitude 3180' '15-ba043na (A12-9700P/8GB/2TB/W10)' 'Omen 17-an012dx'
 'Thinkpad T470s' 'Blade Stealth' 'Latitude 3480'
 'V110-15ISK (i3-6006U/4GB/500GB/W10)' 'Tecra X40-D-10Z' 'GL62M 7RD'
 'Rog GL702VS-BA023T' 'N42-20 Chromebook'
 'R558UA-DM966T (i5-7200U/8GB/128GB/FHD/W10)' 'Rog GL702VM-GC017T'
 'ZenBook UX310UQ-GL026T' 'Rog GL502VM-DS74' 'Inspiron 5767'
 'ThinkPad T470p' 'K556UR-DM621T (i7-7500U/8GB/256GB/GeForce'
 'X541NA (N4200/4GB/1TB/W10)' 'Inspiron 5368' 'Portege X30-D-10X'
 'Portï¿½gï¿½ Z30-C-188' 'TMX349-G2-M-50FS (i5-7200U/8GB/256GB/FHD/W10)'
 'Tecra A50-D-11D' 'X541NA-GO121 (N4200/4GB/1TB/Linux)' 'Pavilion x360'
 'VivoBook L402NA' 'IdeaPad 510-15ISK' 'Rog GL753VD-GC082T'
 'Chromebook C731-C78G' 'Probook 640' 'Envy x360' 'GS73VR Stealth'
 'Portege X30-D-10V' 'G701VO-IH74K (i7-6820HK/32GB/2x' 'Gram 15Z970'
 'Chromebook CB5-571-C1DZ' 'Gram 14Z970' 'Elitebook Folio'
 'IdeaPad 510-15IKB' 'GE72VR 6RF' 'Envy 13-AB077cl' 'Tecra Z50-C-140'
 'Probook 650' 'Tecra Z40-C-12X' 'GP62M Leopard' 'Omen 17-W006na'
 'X751SV-TY001T (N3710/4GB/1TB/GeForce' 'TravelMate P259-G2'
 'Tecra A50-C-1ZV' 'Yoga 700-11ISK' 'IdeaPad Y700-15ACZ' 'Insprion 5767'
 'ZBook Studio' 'Portege Z30-C-1CW' 'ProBook x360' 'Chromebook C738T-C2EJ'
 'Portege Z30-C-16Z' 'Aspire F5-573G-510L' 'Portege X20W-D-10V'
 'Tecra A40-C-1DF' 'ThinkPad T460' 'Q534UX-BHI7T19 (i7-7500U/16GB/2TB'
 '15-bs053od (i7-7500U/6GB/1TB/W10)' 'Rog GL753VE-DS74' 'Inspiron 7579'
 'Portege Z30-C-1CV' 'LifeBook A556' 'Tecra A40-C-1KF'
 '15-bs005nv (i3-6006U/4GB/1TB' 'V110-15IAP (N3350/4GB/128GB/No'
 'ThinkPad T560' 'ZenBook UX310UA-FB485T' 'Spectre 13-V111dx'
 'Aspire ES1-533' 'Rog GL553VE-DS74' 'Nitro 5' 'ENVY -'
 'Portege Z30-C-16H' 'Portege A30-C-1CZ' 'ThinkPad P70' 'Tecra Z40-C-12Z'
 'Inspiron 5568' 'Portï¿½gï¿½ Z30-C-16K' 'Spectre 13-V100nv'
 'Latitude E5570' 'Tecra Z40-C-136' 'Yoga 500-15ISK'
 'V142 (X5-Z8350/2GB/32GB/W10)' 'Tecra A50-C-218' 'Thinkpad L560'
 'GT72S Dominator' 'IdeaPad Y900-17ISK' 'Chromebook C202SA' 'Noteb Pav'
 'Inspiron 5578' '250 G5' 'Aspire ES1-523' 'Inspiron 7378' 'GT62VR 6RD'
 'Rog G752VL-GC088D' 'GS63VR 6RF' 'ROG G701VO' 'Latitude 3570'
 'IdeaPad 300-17ISK' 'Ideapad 700-15ISK' 'GT72VR Dominator'
 'V110-15ISK (i5-6200U/4GB/500GB/W10)' 'Yoga 900S-12ISK' 'Chromebook 13'
 'Rog GL702VM-GC354T' 'Aspire F5-573G' 'GS70 Stealth'
 'G752VY-GC162T (i7-6700HQ/16GB/1TB' 'Latitude E5270' 'Chromebook 15'
 'GE72 Apache' '15-bw011nv (A6-9220/4GB/1TB/FHD/W10)' 'Rog GL552VW-CN470T'
 'Vostro 3559' 'V110-15ISK (i3-6006U/4GB/128GB/W10)' 'Spectre Pro'
 'Portege X30-D-10K' 'Rog GL752VW-T4308T'
 'V131 (X5-Z8350/4GB/32GB/FHD/W10)' 'Omen -'
 '15-bs078cl (i7-7500U/8GB/2TB/W10)' 'ThinkPad P40'
 'L403NA-GA013TS (N3350/4GB/32GB/W10)' 'IdeaPad 500-15ISK' 'GP62M 7RDX'
 'V110-15ISK (i3-6006U/4GB/1TB/No' '15-BA015wm (E2-7110/4GB/500GB/W10)'
 'B51-80 (i5-6200U/8GB/1TB/Radeon' '15-bw002nv (A6-9220/4GB/256GB/Radeon'
 'GP72M 7REX' 'ThinkPad T460s' 'B51-80 (i5-6200U/8GB/1008GB/Radeon'
 'GS40 Phantom' 'Pavilion 15-cb003nv' 'IdeaPad 310-15ISK' '250 G4'
 '320-15ISK (i3-6006U/4GB/1TB/GeForce' 'Stream 14-AX000nv' 'PL60 7RD'
 'X553SA-XX021T (N3050/4GB/500GB/W10)' 'V110-15ISK (i5-6200U/4GB/500GB/No'
 'UX410UA-GV097T (i3-7100U/4GB/256GB/FHD/W10)'
 'B51-80 (i7-6500U/4GB/1008GB/FHD/W7)' 'GS60 Ghost' 'Pavilion 15-BC000nv'
 'Rog GL552VW-DM201T' 'Chromebook Plus' 'Pavilion Power'
 'V110-15ISK (i3-6006U/4GB/1TB/Radeon' 'Rog G752VY-GC229T' 'GS73VR 7RF'
 'FX502VM-DM105T (i7-6700HQ/8GB/1TB/GeForce'
 '15-bs025nv (i5-7200U/8GB/256GB/W10)' 'Aspire E5-774G'
 'FX502VM-AS73 (i7-7700HQ/16GB/1TB' 'C740-C9QX (3205U/2GB/32GB/Chrome'
 'E5 774G' 'SP714-51 (i7-7Y75/8GB/256GB/FHD/W10)' 'Thinkpad T560'
 'GP62MVR 6RF' '15-bw009nv (A12-9720P/6GB/1TB/Radeon' 'Latitude E7270'
 'X540SA-RBPDN09 (N3710/4GB/1TB/W10)' 'GL62M 7RDX' 'GE72VR Apache'
 '15-bs023nv (i3-6006U/4GB/1TB/FHD/W10)' 'GL62 6QF' 'ZenBook UX310UA-WB71'
 'Inspiron 7779' 'Rog GL553VE-FY052T' 'Rog GL502VS'
 'V510-15IKB (i5-7200U/8GB/256GB/FHD/No' 'ThinkPad L460'
 'X541NA-GO020T (N3350/4GB/1TB/W10)' 'Rog G752VT-GC073T'
 'B51-80 (i7-6500U/8GB/1008GB/Radeon' 'GE62 Apache' 'Yoga 500-14IBD'
 'ZenBook UX305CA-UBM1' 'Aspire ES1-531' 'Pavilion 15-AW003nv'
 'Stream 11-Y000na' 'X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce'
 'Yoga 500-14ISK' '15-AC110nv (i7-6500U/6GB/1TB/Radeon'
 'X553SA-XX031T (N3050/4GB/500GB/W10)']

Column: TypeName
['Ultrabook' 'Notebook' 'Netbook' 'Gaming' '2 in 1 Convertible'
 'Workstation']

Column: Inches
[13.3 15.6 15.4 14.  12.  11.6 17.3 10.1 13.5 12.5 13.  18.4 13.9 12.3
 17.  15.  14.1 11.3]

Column: ScreenResolution
['IPS Panel Retina Display 2560x1600' '1440x900' 'Full HD 1920x1080'
 'IPS Panel Retina Display 2880x1800' '1366x768'
 'IPS Panel Full HD 1920x1080' 'IPS Panel Retina Display 2304x1440'
 'IPS Panel Full HD / Touchscreen 1920x1080'
 'Full HD / Touchscreen 1920x1080' 'Touchscreen / Quad HD+ 3200x1800'
 'IPS Panel Touchscreen 1920x1200' 'Touchscreen 2256x1504'
 'Quad HD+ / Touchscreen 3200x1800' 'IPS Panel 1366x768'
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160'
 'IPS Panel Full HD 2160x1440' '4K Ultra HD / Touchscreen 3840x2160'
 'Touchscreen 2560x1440' '1600x900' 'IPS Panel 4K Ultra HD 3840x2160'
 '4K Ultra HD 3840x2160' 'Touchscreen 1366x768'
 'IPS Panel Full HD 1366x768' 'IPS Panel 2560x1440'
 'IPS Panel Full HD 2560x1440' 'IPS Panel Retina Display 2736x1824'
 'Touchscreen 2400x1600' '2560x1440' 'IPS Panel Quad HD+ 2560x1440'
 'IPS Panel Quad HD+ 3200x1800'
 'IPS Panel Quad HD+ / Touchscreen 3200x1800'
 'IPS Panel Touchscreen 1366x768' '1920x1080'
 'IPS Panel Full HD 1920x1200'
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160'
 'IPS Panel Touchscreen 2560x1440' 'Touchscreen / Full HD 1920x1080'
 'Quad HD+ 3200x1800' 'Touchscreen / 4K Ultra HD 3840x2160'
 'IPS Panel Touchscreen 2400x1600']

Column: Cpu
['Intel Core i5 2.3GHz' 'Intel Core i5 1.8GHz'
 'Intel Core i5 7200U 2.5GHz' 'Intel Core i7 2.7GHz'
 'Intel Core i5 3.1GHz' 'AMD A9-Series 9420 3GHz' 'Intel Core i7 2.2GHz'
 'Intel Core i7 8550U 1.8GHz' 'Intel Core i5 8250U 1.6GHz'
 'Intel Core i3 6006U 2GHz' 'Intel Core i7 2.8GHz'
 'Intel Core M m3 1.2GHz' 'Intel Core i7 7500U 2.7GHz'
 'Intel Core i7 2.9GHz' 'Intel Core i3 7100U 2.4GHz'
 'Intel Atom x5-Z8350 1.44GHz' 'Intel Core i5 7300HQ 2.5GHz'
 'AMD E-Series E2-9000e 1.5GHz' 'Intel Core i5 1.6GHz'
 'Intel Core i7 8650U 1.9GHz' 'Intel Atom x5-Z8300 1.44GHz'
 'AMD E-Series E2-6110 1.5GHz' 'AMD A6-Series 9220 2.5GHz'
 'Intel Celeron Dual Core N3350 1.1GHz' 'Intel Core i3 7130U 2.7GHz'
 'Intel Core i7 7700HQ 2.8GHz' 'Intel Core i5 2.0GHz'
 'AMD Ryzen 1700 3GHz' 'Intel Pentium Quad Core N4200 1.1GHz'
 'Intel Atom x5-Z8550 1.44GHz' 'Intel Celeron Dual Core N3060 1.6GHz'
 'Intel Core i5 1.3GHz' 'AMD FX 9830P 3GHz' 'Intel Core i7 7560U 2.4GHz'
 'AMD E-Series 6110 1.5GHz' 'Intel Core i5 6200U 2.3GHz'
 'Intel Core M 6Y75 1.2GHz' 'Intel Core i5 7500U 2.7GHz'
 'Intel Core i3 6006U 2.2GHz' 'AMD A6-Series 9220 2.9GHz'
 'Intel Core i7 6920HQ 2.9GHz' 'Intel Core i5 7Y54 1.2GHz'
 'Intel Core i7 7820HK 2.9GHz' 'Intel Xeon E3-1505M V6 3GHz'
 'Intel Core i7 6500U 2.5GHz' 'AMD E-Series 9000e 1.5GHz'
 'AMD A10-Series A10-9620P 2.5GHz' 'AMD A6-Series A6-9220 2.5GHz'
 'Intel Core i5 2.9GHz' 'Intel Core i7 6600U 2.6GHz'
 'Intel Core i3 6006U 2.0GHz' 'Intel Celeron Dual Core 3205U 1.5GHz'
 'Intel Core i7 7820HQ 2.9GHz' 'AMD A10-Series 9600P 2.4GHz'
 'Intel Core i7 7600U 2.8GHz' 'AMD A8-Series 7410 2.2GHz'
 'Intel Celeron Dual Core 3855U 1.6GHz'
 'Intel Pentium Quad Core N3710 1.6GHz' 'AMD A12-Series 9720P 2.7GHz'
 'Intel Core i5 7300U 2.6GHz' 'AMD A12-Series 9720P 3.6GHz'
 'Intel Celeron Quad Core N3450 1.1GHz'
 'Intel Celeron Dual Core N3060 1.60GHz' 'Intel Core i5 6440HQ 2.6GHz'
 'Intel Core i7 6820HQ 2.7GHz' 'AMD Ryzen 1600 3.2GHz'
 'Intel Core i7 7Y75 1.3GHz' 'Intel Core i5 7440HQ 2.8GHz'
 'Intel Core i7 7660U 2.5GHz' 'Intel Core i7 7700HQ 2.7GHz'
 'Intel Core M m3-7Y30 2.2GHz' 'Intel Core i5 7Y57 1.2GHz'
 'Intel Core i7 6700HQ 2.6GHz' 'Intel Core i3 6100U 2.3GHz'
 'AMD A10-Series 9620P 2.5GHz' 'AMD E-Series 7110 1.8GHz'
 'Intel Celeron Dual Core N3350 2.0GHz' 'AMD A9-Series A9-9420 3GHz'
 'Intel Core i7 6820HK 2.7GHz' 'Intel Core M 7Y30 1.0GHz'
 'Intel Xeon E3-1535M v6 3.1GHz' 'Intel Celeron Quad Core N3160 1.6GHz'
 'Intel Core i5 6300U 2.4GHz' 'Intel Core i3 6100U 2.1GHz'
 'AMD E-Series E2-9000 2.2GHz' 'Intel Celeron Dual Core N3050 1.6GHz'
 'Intel Core M M3-6Y30 0.9GHz' 'AMD A9-Series 9420 2.9GHz'
 'Intel Core i5 6300HQ 2.3GHz' 'AMD A6-Series 7310 2GHz'
 'Intel Atom Z8350 1.92GHz' 'Intel Xeon E3-1535M v5 2.9GHz'
 'Intel Core i5 6260U 1.8GHz' 'Intel Pentium Dual Core N4200 1.1GHz'
 'Intel Celeron Quad Core N3710 1.6GHz' 'Intel Core M 1.2GHz'
 'AMD A12-Series 9700P 2.5GHz' 'Intel Core i7 7500U 2.5GHz'
 'Intel Pentium Dual Core 4405U 2.1GHz' 'AMD A4-Series 7210 2.2GHz'
 'Intel Core i7 6560U 2.2GHz' 'Intel Core M m7-6Y75 1.2GHz'
 'AMD FX 8800P 2.1GHz' 'Intel Core M M7-6Y75 1.2GHz'
 'Intel Core i5 7200U 2.50GHz' 'Intel Core i5 7200U 2.70GHz'
 'Intel Atom X5-Z8350 1.44GHz' 'Intel Core i5 7200U 2.7GHz'
 'Intel Core M 1.1GHz' 'Intel Pentium Dual Core 4405Y 1.5GHz'
 'Intel Pentium Quad Core N3700 1.6GHz' 'Intel Core M 6Y54 1.1GHz'
 'Intel Core i7 6500U 2.50GHz' 'Intel Celeron Dual Core N3350 2GHz'
 'Samsung Cortex A72&A53 2.0GHz' 'AMD E-Series 9000 2.2GHz'
 'Intel Core M 6Y30 0.9GHz' 'AMD A9-Series 9410 2.9GHz']

Column: Ram
['8GB' '16GB' '4GB' '2GB' '12GB' '6GB' '32GB' '24GB' '64GB']

Column: Memory
['128GB SSD' '128GB Flash Storage' '256GB SSD' '512GB SSD' '500GB HDD'
 '256GB Flash Storage' '1TB HDD' '32GB Flash Storage'
 '128GB SSD +  1TB HDD' '256GB SSD +  256GB SSD' '64GB Flash Storage'
 '256GB SSD +  1TB HDD' '256GB SSD +  2TB HDD' '32GB SSD' '2TB HDD'
 '64GB SSD' '1.0TB Hybrid' '512GB SSD +  1TB HDD' '1TB SSD'
 '256GB SSD +  500GB HDD' '128GB SSD +  2TB HDD' '512GB SSD +  512GB SSD'
 '16GB SSD' '16GB Flash Storage' '512GB SSD +  256GB SSD'
 '512GB SSD +  2TB HDD' '64GB Flash Storage +  1TB HDD' '180GB SSD'
 '1TB HDD +  1TB HDD' '32GB HDD' '1TB SSD +  1TB HDD'
 '512GB Flash Storage' '128GB HDD' '240GB SSD' '8GB SSD' '508GB Hybrid'
 '1.0TB HDD' '512GB SSD +  1.0TB Hybrid' '256GB SSD +  1.0TB Hybrid']

Column: Gpu
['Intel Iris Plus Graphics 640' 'Intel HD Graphics 6000'
 'Intel HD Graphics 620' 'AMD Radeon Pro 455'

In [4]:
for col in df["Weight"].unique():
    print(col)

1.37kg
1.34kg
1.86kg
1.83kg
2.1kg
2.04kg
1.3kg
1.6kg
2.2kg
0.92kg
1.22kg
0.98kg
2.5kg
1.62kg
1.91kg
2.3kg
1.35kg
1.88kg
1.89kg
1.65kg
2.71kg
1.2kg
1.44kg
2.8kg
2kg
2.65kg
2.77kg
3.2kg
0.69kg
1.49kg
2.4kg
2.13kg
2.43kg
1.7kg
1.4kg
1.8kg
1.9kg
3kg
1.252kg
2.7kg
2.02kg
1.63kg
1.96kg
1.21kg
2.45kg
1.25kg
1.5kg
2.62kg
1.38kg
1.58kg
1.85kg
1.23kg
1.26kg
2.16kg
2.36kg
2.05kg
1.32kg
1.75kg
0.97kg
2.9kg
2.56kg
1.48kg
1.74kg
1.1kg
1.56kg
2.03kg
1.05kg
4.4kg
1.90kg
1.29kg
2.0kg
1.95kg
2.06kg
1.12kg
1.42kg
3.49kg
3.35kg
2.23kg
4.42kg
2.69kg
2.37kg
4.7kg
3.6kg
2.08kg
4.3kg
1.68kg
1.41kg
4.14kg
2.18kg
2.24kg
2.67kg
2.14kg
1.36kg
2.25kg
2.15kg
2.19kg
2.54kg
3.42kg
1.28kg
2.33kg
1.45kg
2.79kg
1.84kg
2.6kg
2.26kg
3.25kg
1.59kg
1.13kg
1.78kg
1.10kg
1.15kg
1.27kg
1.43kg
2.31kg
1.16kg
1.64kg
2.17kg
1.47kg
3.78kg
1.79kg
0.91kg
1.99kg
4.33kg
1.93kg
1.87kg
2.63kg
3.4kg
3.14kg
1.94kg
1.24kg
4.6kg
4.5kg
2.73kg
1.39kg
2.29kg
2.59kg
2.94kg
1.14kg
3.8kg
3.31kg
1.09kg
3.21kg
1.19kg
1.98kg
1.17kg
4.36kg
1.71kg
2.32kg
4.2kg
1.55kg
0.81kg
1.18kg
2.72kg
1.31kg
0.920kg
3.74kg
1.76kg
1.54kg
2.83kg
2.07kg
2.38kg
3.58kg
1.08kg
2.20kg
2.75kg
1.70kg
2.99kg
1.11kg
2.09kg
4kg
3.0kg
0.99kg
3.52kg
2.591kg
2.21kg
3.3kg
2.191kg
2.34kg
4.0kg

In [5]:
for col in df["Product"].unique():
    print(col)

MacBook Pro
Macbook Air
250 G6
Aspire 3
ZenBook UX430UN
Swift 3
Inspiron 3567
MacBook 12"
IdeaPad 320-15IKB
XPS 13
Vivobook E200HA
Legion Y520-15IKBN
255 G6
Inspiron 5379
15-BS101nv (i7-8550U/8GB/256GB/FHD/W10)
MacBook Air
Inspiron 5570
Latitude 5590
ProBook 470
LapBook 15.6"
E402WA-GA010T (E2-6110/2GB/32GB/W10)
17-ak001nv (A6-9220/4GB/500GB/Radeon
IdeaPad 120S-14IAP
Inspiron 5770
ProBook 450
X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux)
Inspiron 7577
X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce
Aspire A515-51G
Inspiron 7773
IdeaPad 320-15ISK
Rog Strix
X751NV-TY001T (N4200/4GB/1TB/GeForce
Yoga Book
ProBook 430
Inspiron 3576
15-bs002nv (i3-6006U/4GB/128GB/FHD/W10)
VivoBook Max
GS73VR 7RG
X541UA-DM1897 (i3-6006U/4GB/256GB/FHD/Linux)
Vostro 5471
IdeaPad 520S-14IKB
UX410UA-GV350T (i5-8250U/8GB/256GB/FHD/W10)
ZenBook Pro
Stream 14-AX040wm
V310-15ISK (i5-7200U/4GB/1TB/FHD/W10)
FX753VE-GC093 (i7-7700HQ/12GB/1TB/GeForce
Surface Laptop
Inspiron 5370
GL72M 7RDX
Aspire E5-475
FX503VD-E4022T (i7-7700HQ/8GB/1TB/GeForce
IdeaPad 320-15IKBN
Aspire A515-51G-32MX
ProBook 440
IdeaPad 320-15AST
Pavilion 15-CK000nv
FX503VM-E4007T (i7-7700HQ/16GB/1TB
FX550IK-DM018T (FX-9830P/8GB/1TB/Radeon
Aspire 5
Probook 430
Zenbook UX430UA
Spin 5
X541UV-DM1439T (i3-7100U/6GB/256GB/GeForce
Omen 15-ce007nv
15-bs017nv (i7-7500U/8GB/256GB/Radeon
15-bw000nv (E2-9000e/4GB/500GB/Radeon
Envy 13-ad009n
Pavilion 14-BK001nv
Ideapad 310-15ISK
UX430UQ-GV209R (i7-7500U/8GB/256GB/GeForce
GP62M 7REX
Thinkpad T470
VivoBook S15
ThinkPad Yoga
Probook 440
Spectre x360
Inspiron 7570
X705UV-BX074T (i3-6006U/4GB/1TB/GeForce
Spin 3
GS63VR 7RG
Probook 470
E402WA-GA007T (E2-6110/4GB/64GB/W10
Inspiron 5567
Aspire A515-51G-37JS
15-BS078nr (i7-7500U/8GB/1TB/W10)
V110-15IAP (N3350/4GB/1TB/No
FX753VD-GC086T (i5-7300HQ/8GB/1TB
Envy 13-AD007nv
ThinkPad E480
Satellite Pro
ZenBook UX430UA
EliteBook Folio
X541NA (N3350/4GB/1TB/FHD/W10)
GE72MVR 7RG
Aspire A315-51
Inspiron 5577
Inspiron 7567
V110-15IKB (i5-7200U/4GB/128GB/W10)
GE73VR 7RE
EliteBook 840
15-BS103nv (i5-8250U/6GB/256GB/Radeon
Yoga 520-14IKB
ZenBook Flip
Inspiron 5579
X555BP-XX180T (A9-9420/4GB/1TB/Radeon
Aspire A517-51G
Aspire A315-31
GE63VR 7RE
MateBook X
17-bs001nv (i5-7200U/6GB/2TB/Radeon
GT80S 6QF-074US
V310-15IKB (i5-7200U/8GB/1TB
Yoga 920-13IKB
Mi Notebook
XPS 15
Swift 7
Thinkpad Yoga
K147 (N3350/4GB/32GB/FHD/W10)
IdeaPad 320-17IKBR
Blade Pro
Omen 17-W295
V110-15ISK (i5-6200U/4GB/128GB/W10)
Aspire E5-576G
Legion Y720-15IKB
Precision 7520
Aspire 7
ROG GL703VD-GC028T
15-bs018nq (i3-6006U/4GB/500GB/FHD/No
IdeaPad 320-17IKB
Latitude 5490
Portege Z30-C-16L
Alienware 17
Vivobook X541UV-DM1217T
K756UX-T4340T (i5-7200U/8GB/500GB
ZBook 15u
Pro P2540UA-XO0198T
15-rb013nv (E2-9000e/4GB/500GB/W10)
Vostro 5468
Aspire R7
X555QG-DM242T (A10-9620P/4GB/1TB
ROG G703VI-E5062T
Nitro AN515-51
VivoBook Pro
F756UX-T4201D (i7-7500U/8GB/128GB
Yoga 910-13IKB
15-bs015dx (i5-7200U/8GB/1TB/W10)
Rog G701VIK-BA060T
ROG G752VSK-GC493T
X505BP-BR019T (A9-9420/4GB/1TB/Radeon
Vostro 5370
15-BW094nd (A6-9220/8GB/128GB/W10)
Envy 17-U275cl
GT73EVR 7RE
Yoga 720-15IKB
Vostro 3568
V330-15IKB (i7-8550U/8GB/256GB/FHD/W10)
ThinkPad X1
IdeaPad 320-17ISK
Ideapad 320-15IKBN
SP315-51 (i7-7500U/12GB/1TB/FHD/W10)
Thinkpad T570
Chromebook C910-C2ST
FX753VD-GC071T (i7-7700HQ/8GB/1TB/GeForce
17-BS037cl (i3-6006U/8GB/1TB/W10)
V330-15IKB (i5-8250U/8GB/256GB/FHD/W10)
Aspire A715-71G
Precision 7720
IdeaPad 310-15ABR
ZenBook UX530UQ-PRO
VivoBook S14
Rog GL702VS-GC095T
GL553VE-FY082T (i7-7700HQ/8GB/1TB
IdeaPad 320-15IAP
EliteBook x360
IdeaPad 720S-13IKB
GE63VR 7RF
ES1-523-84K7 (A8-7410/8GB/256GB/FHD/W10)
VivoBook Flip
ThinkPad 13
ProBook 640
TravelMate B
Elitebook 840
ZenBook UX410UA-GV183T
Aspire E5-575
Elitebook 820
GL72M 7REX
UX510UX-CN269T (i7-7500U/8GB/256GB
V310-15ISK (i3-6006U/4GB/1TB/FHD/W10)
FX553VD-FY647T (i7-7700HQ/8GB/256GB/GeForce
Elitebook 850
X541NA (N3350/4GB/1TB/Linux)
Inspiron 3552
IdeaPad 320-15ABR
Stream 14-AX001nv
GP72MVR 7RFX
Zbook 15
Tecra A50-C-21G
Latitude 7480
Zenbook UX410UA-GV027T
15-AY023na (N3710/8GB/2TB/W10)
Elitebook 1040
IdeaPad 110-17ACL
15-bw003nv (A9-Series-9420/4GB/256GB/FHD/W10)
Yoga 11e
VivoBook E403NA
Omen 17-w212nv
V310-15ISK (i3-6006U/4GB/128GB/FHD/No
ROG Strix
IdeaPad 720S-14IKB
Zenbook Flip
Thinkpad X1
Ideapad 510S-13IKB
Precision 3510
Precision 5520
Rog GL753VD-GC042T
Rog GL753VE-GC070T
Leopard GP72M
15-BW004nv (A9-9420/4GB/256GB/Radeon
ThinkPad E580
ThinkPad L470
Precision M5520
FX753VD-GC461T (i7-7700HQ/16GB/1TB
GE73VR 7RF
Zenbook 3
Portege Z30-C-16P
Lenovo IdeaPad
ThinkPad P51
Thinkpad T470p
15-BS028nv (i3-6006U/4GB/1TB/Radeon
Latitude 3380
EliteBook 1040
LapBook 12.3
ProBook 650
X542UQ-DM117 (i3-7100U/8GB/1TB/GeForce
Latitude 5480
Omen 17-w207nv
FlexBook Edge
Chromebook 3
Thinkpad 13
IdeaPad 320s-14IKB
Thinkpad P51
15-ra044nv (N3060/4GB/500GB/W10)
Pixelbook (Core
ThinkPad T470s
ThinkPad X270
Omen 15-AX205na
Aspire ES1-572
Precision 3520
GV62 7RD-1686NL
15-bs024nv (i5-7200U/8GB/128GB/W10)
ThinkPad T470
Inspiron 3168
17-BS092ND (i3-6006U/8GB/256GB/W10)
Pro P2540UA-AB51
IdeaPad 510s-14IKB
X541NA-PD1003Y (N4200/4GB/500GB/W10)
Omen 17-an006nv
Thinkpad T460s
Latitude 7390
Latitude E5470
Portege X30-D-10J
Lapbook 15,6
ThinkPad E570
Thinkpad X270
Zenbook UX390UA
Thinkpad E570
Portege X30-D-10L
Rog G752VL-UH71T
Thinkpad X260
Ideapad 520-15IKBR
ThinkPad L570
VivoBook E201NA
15-BS026nv (i5-7200U/8GB/256GB/Radeon
IdeaPad 320-14IAP
Chromebook N23
ZenBook UX510UX-CN211T
Aspire A515-51G-59QF
Envy 13-AB002nv
Vostro 5568
VivoBook E12
15-bs190od (i5-8250U/4GB/1TB/W10)
ROG Zephyrus
Probook 450
FX753VE-GC155T (i7-7700HQ/16GB/1TB
Spectre X360
Latitude 5580
Zenbook UX510UW-FI095T
SmartBook Edge
Omen 15-ce006nv
Thinkpad E470
Envy 13-AB020nr
VivoBook X540YA-XX519T
ThinkPad E470
V310-15ISK (i5-6200U/4GB/1TB/FHD/No
ThinkPad T570
17-X047na (i3-6006U/8GB/1TB/W10)
A541NA-GO342 (N3350/4GB/500GB/Linux)
SmartBook 130
15-bw007nv (A10-9620P/6GB/128GB/Radeon
Spin SP111-31
V330-15IKB (i3-7130U/4GB/128GB/FHD/W10)
EliteBook 1030
Thinkpad P71
FX553VD-DM627T (i5-7300HQ/8GB/1TB
Lifebook A557
ZBook 17
14-am079na (N3710/8GB/2TB/W10)
15-cd005nv (A9-9420/6GB/256GB/Radeon
V330-15IKB (i5-8250U/4GB/500GB/FHD/W10)
SmartBook 141
Tecra X40-D-10H
IdeaPad Y910-17ISK
GT73VR Titan
Chromebook 11
GT80S 6QE
Omen 17-AN010nv
Ideapad 320-15IKBR
TP501UA-CJ131T (i5-7200U/8GB/1TB/W10)
Inspiron 3179
Notebook Odyssey
V320-17ISK (i3-6006U/4GB/500GB/FHD/No
IdeaPad 110-15ISK
Latitude 5289
EliteBook 850
Aspire 1
Laptop MSI
GS63VR 7RF
Tecra Z50-C-144
IdeaPad 310-15IKB
Swift SF114-31-P5HY
Inspiron 7559
FX753VD-GC007T (i7-7700HQ/8GB/1TB
GT62VR 7RE
CB5-132T-C9KK (N3160/4GB/32GB/Chrome
LifeBook A557
SmartBook 140
Q304UA-BHI5T11 (i5-7200U/6GB/1TB/FHD/W10)
ZenBook 3
V330-15IKB (i5-8250U/4GB/256GB/FHD/W10)
Ideapad 320-15ISK
X541NA-GO414T (N3350/8GB/1TB/W10)
IdeaPad 100S-14IBR
17-AK091ND (A9-9420/8GB/1TB/W10)
ROG GL553VE-FY022
Extensa EX2540
Portege Z30-C-16J
ROG G701VI
A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce
GL62M 7REX
Tecra A50-D-11M
IdeaPad Y700-15ISK
Latitude E7470
Ideapad 320-15IAP
15-ay047nv (i3-6006U/6GB/1TB/Radeon
GP72VR Leopard
Latitude 3580
15-bs012nv (i7-7500U/8GB/1TB/Radeon
Tecra Z50-D-10E
V310-15ISK (i5-7200U/8GB/1TB
Yoga 720-13IKB
Pavilion X360
GP62 7RDX
Chromebook X360
Gram 15Z975
Aspire VX5-591G
GV62M 7RD
L502NA-GO052T (N3350/4GB/128GB/W10)
Alienware 15
17-bs000nv I3
Yoga 730
17-Y002nv (A10-9600P/6GB/2TB/Radeon
V110-15ISK (3855U/4GB/500GB/W10)
Chromebook 14
IdeaPad 520s-14IKB
TravelMate B117-M
Chromebook Flip
Portege Z30T-C-133
15-bs011nv (i7-7500U/4GB/500GB/Radeon
V310-15IKB (i5-7200U/4GB/1TB/FHD/W10)
V310-15ISK (i3-6006U/4GB/500GB/No
ThinkPad P51s
Thinkpad T460p
17-ak002nv (A10-9620P/6GB/2TB/Radeon
110-15ACL (A6-7310/4GB/500GB/W10)
Smartbook 142
V310-15IKB (i5-7200U/4GB/1TB/No
Inspiron 5378
15-BW037na (A9-9420/4GB/1TB/Radeon
Predator 17
15-BW091ND (A9-9420/6GB/1TB
Extensa EX2540-58KR
V310-15IKB (i7-7500U/4GB/1TB/FHD/W10)
ZBook 15
Inspiron 7560
Tecra X40-D-10G
Flex 5
Thinkpad P51s
Notebook 9
Zbook 17
N23 (N3060/4GB/128GB/W10)
X550VX-XX015D (i5-6300HQ/4GB/1TB/GeForce
Thinkpad T460
Pro P2540UA-XO0192R
Yoga 900-13ISK
15-cb003na (i5-7300HQ/8GB/1TB
Latitude 7280
Zenbook UX330UA-AH5Q
TravelMate P238-M
X751NV-TY001 (N4200/4GB/1TB/GeForce
Tecra A40-C-1E5
EliteBook 820
Q524UQ-BHI7T15 (i7-7500U/12GB/2TB/GeForce
Thinkpad P50
Vivobook Max
Rog G752VS-BA171T
Tecra Z40-C-161
IdeaPad 110-15IBR
GS43VR 7RE
GL62M (i5-7300HQ/8GB/1TB
Predator G9-793
FX502VM-DM560T (i7-7700HQ/8GB/1TB
K146 (N3350/4GB/32GB/W10)
Yoga 510-15IKB
R417NA-RS01 (N3350/4GB/32GB/W10)
Pro P2540UA-XS51
Latitude 3180
15-ba043na (A12-9700P/8GB/2TB/W10)
Omen 17-an012dx
Thinkpad T470s
Blade Stealth
Latitude 3480
V110-15ISK (i3-6006U/4GB/500GB/W10)
Tecra X40-D-10Z
GL62M 7RD
Rog GL702VS-BA023T
N42-20 Chromebook
R558UA-DM966T (i5-7200U/8GB/128GB/FHD/W10)
Rog GL702VM-GC017T
ZenBook UX310UQ-GL026T
Rog GL502VM-DS74
Inspiron 5767
ThinkPad T470p
K556UR-DM621T (i7-7500U/8GB/256GB/GeForce
X541NA (N4200/4GB/1TB/W10)
Inspiron 5368
Portege X30-D-10X
Portï¿½gï¿½ Z30-C-188
TMX349-G2-M-50FS (i5-7200U/8GB/256GB/FHD/W10)
Tecra A50-D-11D
X541NA-GO121 (N4200/4GB/1TB/Linux)
Pavilion x360
VivoBook L402NA
IdeaPad 510-15ISK
Rog GL753VD-GC082T
Chromebook C731-C78G
Probook 640
Envy x360
GS73VR Stealth
Portege X30-D-10V
G701VO-IH74K (i7-6820HK/32GB/2x
Gram 15Z970
Chromebook CB5-571-C1DZ
Gram 14Z970
Elitebook Folio
IdeaPad 510-15IKB
GE72VR 6RF
Envy 13-AB077cl
Tecra Z50-C-140
Probook 650
Tecra Z40-C-12X
GP62M Leopard
Omen 17-W006na
X751SV-TY001T (N3710/4GB/1TB/GeForce
TravelMate P259-G2
Tecra A50-C-1ZV
Yoga 700-11ISK
IdeaPad Y700-15ACZ
Insprion 5767
ZBook Studio
Portege Z30-C-1CW
ProBook x360
Chromebook C738T-C2EJ
Portege Z30-C-16Z
Aspire F5-573G-510L
Portege X20W-D-10V
Tecra A40-C-1DF
ThinkPad T460
Q534UX-BHI7T19 (i7-7500U/16GB/2TB
15-bs053od (i7-7500U/6GB/1TB/W10)
Rog GL753VE-DS74
Inspiron 7579
Portege Z30-C-1CV
LifeBook A556
Tecra A40-C-1KF
15-bs005nv (i3-6006U/4GB/1TB
V110-15IAP (N3350/4GB/128GB/No
ThinkPad T560
ZenBook UX310UA-FB485T
Spectre 13-V111dx
Aspire ES1-533
Rog GL553VE-DS74
Nitro 5
ENVY -
Portege Z30-C-16H
Portege A30-C-1CZ
ThinkPad P70
Tecra Z40-C-12Z
Inspiron 5568
Portï¿½gï¿½ Z30-C-16K
Spectre 13-V100nv
Latitude E5570
Tecra Z40-C-136
Yoga 500-15ISK
V142 (X5-Z8350/2GB/32GB/W10)
Tecra A50-C-218
Thinkpad L560
GT72S Dominator
IdeaPad Y900-17ISK
Chromebook C202SA
Noteb Pav
Inspiron 5578
250 G5
Aspire ES1-523
Inspiron 7378
GT62VR 6RD
Rog G752VL-GC088D
GS63VR 6RF
ROG G701VO
Latitude 3570
IdeaPad 300-17ISK
Ideapad 700-15ISK
GT72VR Dominator
V110-15ISK (i5-6200U/4GB/500GB/W10)
Yoga 900S-12ISK
Chromebook 13
Rog GL702VM-GC354T
Aspire F5-573G
GS70 Stealth
G752VY-GC162T (i7-6700HQ/16GB/1TB
Latitude E5270
Chromebook 15
GE72 Apache
15-bw011nv (A6-9220/4GB/1TB/FHD/W10)
Rog GL552VW-CN470T
Vostro 3559
V110-15ISK (i3-6006U/4GB/128GB/W10)
Spectre Pro
Portege X30-D-10K
Rog GL752VW-T4308T
V131 (X5-Z8350/4GB/32GB/FHD/W10)
Omen -
15-bs078cl (i7-7500U/8GB/2TB/W10)
ThinkPad P40
L403NA-GA013TS (N3350/4GB/32GB/W10)
IdeaPad 500-15ISK
GP62M 7RDX
V110-15ISK (i3-6006U/4GB/1TB/No
15-BA015wm (E2-7110/4GB/500GB/W10)
B51-80 (i5-6200U/8GB/1TB/Radeon
15-bw002nv (A6-9220/4GB/256GB/Radeon
GP72M 7REX
ThinkPad T460s
B51-80 (i5-6200U/8GB/1008GB/Radeon
GS40 Phantom
Pavilion 15-cb003nv
IdeaPad 310-15ISK
250 G4
320-15ISK (i3-6006U/4GB/1TB/GeForce
Stream 14-AX000nv
PL60 7RD
X553SA-XX021T (N3050/4GB/500GB/W10)
V110-15ISK (i5-6200U/4GB/500GB/No
UX410UA-GV097T (i3-7100U/4GB/256GB/FHD/W10)
B51-80 (i7-6500U/4GB/1008GB/FHD/W7)
GS60 Ghost
Pavilion 15-BC000nv
Rog GL552VW-DM201T
Chromebook Plus
Pavilion Power
V110-15ISK (i3-6006U/4GB/1TB/Radeon
Rog G752VY-GC229T
GS73VR 7RF
FX502VM-DM105T (i7-6700HQ/8GB/1TB/GeForce
15-bs025nv (i5-7200U/8GB/256GB/W10)
Aspire E5-774G
FX502VM-AS73 (i7-7700HQ/16GB/1TB
C740-C9QX (3205U/2GB/32GB/Chrome
E5 774G
SP714-51 (i7-7Y75/8GB/256GB/FHD/W10)
Thinkpad T560
GP62MVR 6RF
15-bw009nv (A12-9720P/6GB/1TB/Radeon
Latitude E7270
X540SA-RBPDN09 (N3710/4GB/1TB/W10)
GL62M 7RDX
GE72VR Apache
15-bs023nv (i3-6006U/4GB/1TB/FHD/W10)
GL62 6QF
ZenBook UX310UA-WB71
Inspiron 7779
Rog GL553VE-FY052T
Rog GL502VS
V510-15IKB (i5-7200U/8GB/256GB/FHD/No
ThinkPad L460
X541NA-GO020T (N3350/4GB/1TB/W10)
Rog G752VT-GC073T
B51-80 (i7-6500U/8GB/1008GB/Radeon
GE62 Apache
Yoga 500-14IBD
ZenBook UX305CA-UBM1
Aspire ES1-531
Pavilion 15-AW003nv
Stream 11-Y000na
X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce
Yoga 500-14ISK
15-AC110nv (i7-6500U/6GB/1TB/Radeon
X553SA-XX031T (N3050/4GB/500GB/W10)

In [ ]:
Company_list = df['Company'].unique().tolist()
Company_dict = {Company: i+1 for i, Company in enumerate(Company_list)}
print(Company_dict)
df['Company'] = df['Company'].map(Company_dict)

{'Apple': 1, 'HP': 2, 'Acer': 3, 'Asus': 4, 'Dell': 5, 'Lenovo': 6, 'Chuwi': 7, 'MSI': 8, 'Microsoft': 9, 'Toshiba': 10, 'Huawei': 11, 'Xiaomi': 12, 'Vero': 13, 'Razer': 14, 'Mediacom': 15, 'Samsung': 16, 'Google': 17, 'Fujitsu': 18, 'LG': 19}

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\3759145418.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company'] = df['Company'].map(Company_dict)

In [ ]:
Product_list = df['Product'].unique().tolist()
Product_dict = {Product: i+1 for i, Product in enumerate(Product_list)}
print(Product_dict)
df['Product'] = df['Product'].map(Product_dict)

{'MacBook Pro': 1, 'Macbook Air': 2, '250 G6': 3, 'Aspire 3': 4, 'ZenBook UX430UN': 5, 'Swift 3': 6, 'Inspiron 3567': 7, 'MacBook 12"': 8, 'IdeaPad 320-15IKB': 9, 'XPS 13': 10, 'Vivobook E200HA': 11, 'Legion Y520-15IKBN': 12, '255 G6': 13, 'Inspiron 5379': 14, '15-BS101nv (i7-8550U/8GB/256GB/FHD/W10)': 15, 'MacBook Air': 16, 'Inspiron 5570': 17, 'Latitude 5590': 18, 'ProBook 470': 19, 'LapBook 15.6"': 20, 'E402WA-GA010T (E2-6110/2GB/32GB/W10)': 21, '17-ak001nv (A6-9220/4GB/500GB/Radeon': 22, 'IdeaPad 120S-14IAP': 23, 'Inspiron 5770': 24, 'ProBook 450': 25, 'X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux)': 26, 'Inspiron 7577': 27, 'X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce': 28, 'Aspire A515-51G': 29, 'Inspiron 7773': 30, 'IdeaPad 320-15ISK': 31, 'Rog Strix': 32, 'X751NV-TY001T (N4200/4GB/1TB/GeForce': 33, 'Yoga Book': 34, 'ProBook 430': 35, 'Inspiron 3576': 36, '15-bs002nv (i3-6006U/4GB/128GB/FHD/W10)': 37, 'VivoBook Max': 38, 'GS73VR 7RG': 39, 'X541UA-DM1897 (i3-6006U/4GB/256GB/FHD/Linux)': 40, 'Vostro 5471': 41, 'IdeaPad 520S-14IKB': 42, 'UX410UA-GV350T (i5-8250U/8GB/256GB/FHD/W10)': 43, 'ZenBook Pro': 44, 'Stream 14-AX040wm': 45, 'V310-15ISK (i5-7200U/4GB/1TB/FHD/W10)': 46, 'FX753VE-GC093 (i7-7700HQ/12GB/1TB/GeForce': 47, 'Surface Laptop': 48, 'Inspiron 5370': 49, 'GL72M 7RDX': 50, 'Aspire E5-475': 51, 'FX503VD-E4022T (i7-7700HQ/8GB/1TB/GeForce': 52, 'IdeaPad 320-15IKBN': 53, 'Aspire A515-51G-32MX': 54, 'ProBook 440': 55, 'IdeaPad 320-15AST': 56, 'Pavilion 15-CK000nv': 57, 'FX503VM-E4007T (i7-7700HQ/16GB/1TB': 58, 'FX550IK-DM018T (FX-9830P/8GB/1TB/Radeon': 59, 'Aspire 5': 60, 'Probook 430': 61, 'Zenbook UX430UA': 62, 'Spin 5': 63, 'X541UV-DM1439T (i3-7100U/6GB/256GB/GeForce': 64, 'Omen 15-ce007nv': 65, '15-bs017nv (i7-7500U/8GB/256GB/Radeon': 66, '15-bw000nv (E2-9000e/4GB/500GB/Radeon': 67, 'Envy 13-ad009n': 68, 'Pavilion 14-BK001nv': 69, 'Ideapad 310-15ISK': 70, 'UX430UQ-GV209R (i7-7500U/8GB/256GB/GeForce': 71, 'GP62M 7REX': 72, 'Thinkpad T470': 73, 'VivoBook S15': 74, 'ThinkPad Yoga': 75, 'Probook 440': 76, 'Spectre x360': 77, 'Inspiron 7570': 78, 'X705UV-BX074T (i3-6006U/4GB/1TB/GeForce': 79, 'Spin 3': 80, 'GS63VR 7RG': 81, 'Probook 470': 82, 'E402WA-GA007T (E2-6110/4GB/64GB/W10': 83, 'Inspiron 5567': 84, 'Aspire A515-51G-37JS': 85, '15-BS078nr (i7-7500U/8GB/1TB/W10)': 86, 'V110-15IAP (N3350/4GB/1TB/No': 87, 'FX753VD-GC086T (i5-7300HQ/8GB/1TB': 88, 'Envy 13-AD007nv': 89, 'ThinkPad E480': 90, 'Satellite Pro': 91, 'ZenBook UX430UA': 92, 'EliteBook Folio': 93, 'X541NA (N3350/4GB/1TB/FHD/W10)': 94, 'GE72MVR 7RG': 95, 'Aspire A315-51': 96, 'Inspiron 5577': 97, 'Inspiron 7567': 98, 'V110-15IKB (i5-7200U/4GB/128GB/W10)': 99, 'GE73VR 7RE': 100, 'EliteBook 840': 101, '15-BS103nv (i5-8250U/6GB/256GB/Radeon': 102, 'Yoga 520-14IKB': 103, 'ZenBook Flip': 104, 'Inspiron 5579': 105, 'X555BP-XX180T (A9-9420/4GB/1TB/Radeon': 106, 'Aspire A517-51G': 107, 'Aspire A315-31': 108, 'GE63VR 7RE': 109, 'MateBook X': 110, '17-bs001nv (i5-7200U/6GB/2TB/Radeon': 111, 'GT80S 6QF-074US': 112, 'V310-15IKB (i5-7200U/8GB/1TB': 113, 'Yoga 920-13IKB': 114, 'Mi Notebook': 115, 'XPS 15': 116, 'Swift 7': 117, 'Thinkpad Yoga': 118, 'K147 (N3350/4GB/32GB/FHD/W10)': 119, 'IdeaPad 320-17IKBR': 120, 'Blade Pro': 121, 'Omen 17-W295': 122, 'V110-15ISK (i5-6200U/4GB/128GB/W10)': 123, 'Aspire E5-576G': 124, 'Legion Y720-15IKB': 125, 'Precision 7520': 126, 'Aspire 7': 127, 'ROG GL703VD-GC028T': 128, '15-bs018nq (i3-6006U/4GB/500GB/FHD/No': 129, 'IdeaPad 320-17IKB': 130, 'Latitude 5490': 131, 'Portege Z30-C-16L': 132, 'Alienware 17': 133, 'Vivobook X541UV-DM1217T': 134, 'K756UX-T4340T (i5-7200U/8GB/500GB': 135, 'ZBook 15u': 136, 'Pro P2540UA-XO0198T': 137, '15-rb013nv (E2-9000e/4GB/500GB/W10)': 138, 'Vostro 5468': 139, 'Aspire R7': 140, 'X555QG-DM242T (A10-9620P/4GB/1TB': 141, 'ROG G703VI-E5062T': 142, 'Nitro AN515-51': 143, 'VivoBook Pro': 144, 'F756UX-T4201D (i7-7500U/8GB/128GB': 145, 'Yoga 910-13IKB': 146, '15-bs015dx (i5-7200U/8GB/1TB/W10)': 147, 'Rog G701VIK-BA060T': 148, 'ROG G752VSK-GC493T': 149, 'X505BP-BR019T (A9-9420/4GB/1TB/Radeon': 150, 'Vostro 5370': 151, '15-BW094nd (A6-9220/8GB/128GB/W10)': 152, 'Envy 17-U275cl': 153, 'GT73EVR 7RE': 154, 'Yoga 720-15IKB': 155, 'Vostro 3568': 156, 'V330-15IKB (i7-8550U/8GB/256GB/FHD/W10)': 157, 'ThinkPad X1': 158, 'IdeaPad 320-17ISK': 159, 'Ideapad 320-15IKBN': 160, 'SP315-51 (i7-7500U/12GB/1TB/FHD/W10)': 161, 'Thinkpad T570': 162, 'Chromebook C910-C2ST': 163, 'FX753VD-GC071T (i7-7700HQ/8GB/1TB/GeForce': 164, '17-BS037cl (i3-6006U/8GB/1TB/W10)': 165, 'V330-15IKB (i5-8250U/8GB/256GB/FHD/W10)': 166, 'Aspire A715-71G': 167, 'Precision 7720': 168, 'IdeaPad 310-15ABR': 169, 'ZenBook UX530UQ-PRO': 170, 'VivoBook S14': 171, 'Rog GL702VS-GC095T': 172, 'GL553VE-FY082T (i7-7700HQ/8GB/1TB': 173, 'IdeaPad 320-15IAP': 174, 'EliteBook x360': 175, 'IdeaPad 720S-13IKB': 176, 'GE63VR 7RF': 177, 'ES1-523-84K7 (A8-7410/8GB/256GB/FHD/W10)': 178, 'VivoBook Flip': 179, 'ThinkPad 13': 180, 'ProBook 640': 181, 'TravelMate B': 182, 'Elitebook 840': 183, 'ZenBook UX410UA-GV183T': 184, 'Aspire E5-575': 185, 'Elitebook 820': 186, 'GL72M 7REX': 187, 'UX510UX-CN269T (i7-7500U/8GB/256GB': 188, 'V310-15ISK (i3-6006U/4GB/1TB/FHD/W10)': 189, 'FX553VD-FY647T (i7-7700HQ/8GB/256GB/GeForce': 190, 'Elitebook 850': 191, 'X541NA (N3350/4GB/1TB/Linux)': 192, 'Inspiron 3552': 193, 'IdeaPad 320-15ABR': 194, 'Stream 14-AX001nv': 195, 'GP72MVR 7RFX': 196, 'Zbook 15': 197, 'Tecra A50-C-21G': 198, 'Latitude 7480': 199, 'Zenbook UX410UA-GV027T': 200, '15-AY023na (N3710/8GB/2TB/W10)': 201, 'Elitebook 1040': 202, 'IdeaPad 110-17ACL': 203, '15-bw003nv (A9-Series-9420/4GB/256GB/FHD/W10)': 204, 'Yoga 11e': 205, 'VivoBook E403NA': 206, 'Omen 17-w212nv': 207, 'V310-15ISK (i3-6006U/4GB/128GB/FHD/No': 208, 'ROG Strix': 209, 'IdeaPad 720S-14IKB': 210, 'Zenbook Flip': 211, 'Thinkpad X1': 212, 'Ideapad 510S-13IKB': 213, 'Precision 3510': 214, 'Precision 5520': 215, 'Rog GL753VD-GC042T': 216, 'Rog GL753VE-GC070T': 217, 'Leopard GP72M': 218, '15-BW004nv (A9-9420/4GB/256GB/Radeon': 219, 'ThinkPad E580': 220, 'ThinkPad L470': 221, 'Precision M5520': 222, 'FX753VD-GC461T (i7-7700HQ/16GB/1TB': 223, 'GE73VR 7RF': 224, 'Zenbook 3': 225, 'Portege Z30-C-16P': 226, 'Lenovo IdeaPad': 227, 'ThinkPad P51': 228, 'Thinkpad T470p': 229, '15-BS028nv (i3-6006U/4GB/1TB/Radeon': 230, 'Latitude 3380': 231, 'EliteBook 1040': 232, 'LapBook 12.3': 233, 'ProBook 650': 234, 'X542UQ-DM117 (i3-7100U/8GB/1TB/GeForce': 235, 'Latitude 5480': 236, 'Omen 17-w207nv': 237, 'FlexBook Edge': 238, 'Chromebook 3': 239, 'Thinkpad 13': 240, 'IdeaPad 320s-14IKB': 241, 'Thinkpad P51': 242, '15-ra044nv (N3060/4GB/500GB/W10)': 243, 'Pixelbook (Core': 244, 'ThinkPad T470s': 245, 'ThinkPad X270': 246, 'Omen 15-AX205na': 247, 'Aspire ES1-572': 248, 'Precision 3520': 249, 'GV62 7RD-1686NL': 250, '15-bs024nv (i5-7200U/8GB/128GB/W10)': 251, 'ThinkPad T470': 252, 'Inspiron 3168': 253, '17-BS092ND (i3-6006U/8GB/256GB/W10)': 254, 'Pro P2540UA-AB51': 255, 'IdeaPad 510s-14IKB': 256, 'X541NA-PD1003Y (N4200/4GB/500GB/W10)': 257, 'Omen 17-an006nv': 258, 'Thinkpad T460s': 259, 'Latitude 7390': 260, 'Latitude E5470': 261, 'Portege X30-D-10J': 262, 'Lapbook 15,6': 263, 'ThinkPad E570': 264, 'Thinkpad X270': 265, 'Zenbook UX390UA': 266, 'Thinkpad E570': 267, 'Portege X30-D-10L': 268, 'Rog G752VL-UH71T': 269, 'Thinkpad X260': 270, 'Ideapad 520-15IKBR': 271, 'ThinkPad L570': 272, 'VivoBook E201NA': 273, '15-BS026nv (i5-7200U/8GB/256GB/Radeon': 274, 'IdeaPad 320-14IAP': 275, 'Chromebook N23': 276, 'ZenBook UX510UX-CN211T': 277, 'Aspire A515-51G-59QF': 278, 'Envy 13-AB002nv': 279, 'Vostro 5568': 280, 'VivoBook E12': 281, '15-bs190od (i5-8250U/4GB/1TB/W10)': 282, 'ROG Zephyrus': 283, 'Probook 450': 284, 'FX753VE-GC155T (i7-7700HQ/16GB/1TB': 285, 'Spectre X360': 286, 'Latitude 5580': 287, 'Zenbook UX510UW-FI095T': 288, 'SmartBook Edge': 289, 'Omen 15-ce006nv': 290, 'Thinkpad E470': 291, 'Envy 13-AB020nr': 292, 'VivoBook X540YA-XX519T': 293, 'ThinkPad E470': 294, 'V310-15ISK (i5-6200U/4GB/1TB/FHD/No': 295, 'ThinkPad T570': 296, '17-X047na (i3-6006U/8GB/1TB/W10)': 297, 'A541NA-GO342 (N3350/4GB/500GB/Linux)': 298, 'SmartBook 130': 299, '15-bw007nv (A10-9620P/6GB/128GB/Radeon': 300, 'Spin SP111-31': 301, 'V330-15IKB (i3-7130U/4GB/128GB/FHD/W10)': 302, 'EliteBook 1030': 303, 'Thinkpad P71': 304, 'FX553VD-DM627T (i5-7300HQ/8GB/1TB': 305, 'Lifebook A557': 306, 'ZBook 17': 307, '14-am079na (N3710/8GB/2TB/W10)': 308, '15-cd005nv (A9-9420/6GB/256GB/Radeon': 309, 'V330-15IKB (i5-8250U/4GB/500GB/FHD/W10)': 310, 'SmartBook 141': 311, 'Tecra X40-D-10H': 312, 'IdeaPad Y910-17ISK': 313, 'GT73VR Titan': 314, 'Chromebook 11': 315, 'GT80S 6QE': 316, 'Omen 17-AN010nv': 317, 'Ideapad 320-15IKBR': 318, 'TP501UA-CJ131T (i5-7200U/8GB/1TB/W10)': 319, 'Inspiron 3179': 320, 'Notebook Odyssey': 321, 'V320-17ISK (i3-6006U/4GB/500GB/FHD/No': 322, 'IdeaPad 110-15ISK': 323, 'Latitude 5289': 324, 'EliteBook 850': 325, 'Aspire 1': 326, 'Laptop MSI': 327, 'GS63VR 7RF': 328, 'Tecra Z50-C-144': 329, 'IdeaPad 310-15IKB': 330, 'Swift SF114-31-P5HY': 331, 'Inspiron 7559': 332, 'FX753VD-GC007T (i7-7700HQ/8GB/1TB': 333, 'GT62VR 7RE': 334, 'CB5-132T-C9KK (N3160/4GB/32GB/Chrome': 335, 'LifeBook A557': 336, 'SmartBook 140': 337, 'Q304UA-BHI5T11 (i5-7200U/6GB/1TB/FHD/W10)': 338, 'ZenBook 3': 339, 'V330-15IKB (i5-8250U/4GB/256GB/FHD/W10)': 340, 'Ideapad 320-15ISK': 341, 'X541NA-GO414T (N3350/8GB/1TB/W10)': 342, 'IdeaPad 100S-14IBR': 343, '17-AK091ND (A9-9420/8GB/1TB/W10)': 344, 'ROG GL553VE-FY022': 345, 'Extensa EX2540': 346, 'Portege Z30-C-16J': 347, 'ROG G701VI': 348, 'A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce': 349, 'GL62M 7REX': 350, 'Tecra A50-D-11M': 351, 'IdeaPad Y700-15ISK': 352, 'Latitude E7470': 353, 'Ideapad 320-15IAP': 354, '15-ay047nv (i3-6006U/6GB/1TB/Radeon': 355, 'GP72VR Leopard': 356, 'Latitude 3580': 357, '15-bs012nv (i7-7500U/8GB/1TB/Radeon': 358, 'Tecra Z50-D-10E': 359, 'V310-15ISK (i5-7200U/8GB/1TB': 360, 'Yoga 720-13IKB': 361, 'Pavilion X360': 362, 'GP62 7RDX': 363, 'Chromebook X360': 364, 'Gram 15Z975': 365, 'Aspire VX5-591G': 366, 'GV62M 7RD': 367, 'L502NA-GO052T (N3350/4GB/128GB/W10)': 368, 'Alienware 15': 369, '17-bs000nv I3': 370, 'Yoga 730': 371, '17-Y002nv (A10-9600P/6GB/2TB/Radeon': 372, 'V110-15ISK (3855U/4GB/500GB/W10)': 373, 'Chromebook 14': 374, 'IdeaPad 520s-14IKB': 375, 'TravelMate B117-M': 376, 'Chromebook Flip': 377, 'Portege Z30T-C-133': 378, '15-bs011nv (i7-7500U/4GB/500GB/Radeon': 379, 'V310-15IKB (i5-7200U/4GB/1TB/FHD/W10)': 380, 'V310-15ISK (i3-6006U/4GB/500GB/No': 381, 'ThinkPad P51s': 382, 'Thinkpad T460p': 383, '17-ak002nv (A10-9620P/6GB/2TB/Radeon': 384, '110-15ACL (A6-7310/4GB/500GB/W10)': 385, 'Smartbook 142': 386, 'V310-15IKB (i5-7200U/4GB/1TB/No': 387, 'Inspiron 5378': 388, '15-BW037na (A9-9420/4GB/1TB/Radeon': 389, 'Predator 17': 390, '15-BW091ND (A9-9420/6GB/1TB': 391, 'Extensa EX2540-58KR': 392, 'V310-15IKB (i7-7500U/4GB/1TB/FHD/W10)': 393, 'ZBook 15': 394, 'Inspiron 7560': 395, 'Tecra X40-D-10G': 396, 'Flex 5': 397, 'Thinkpad P51s': 398, 'Notebook 9': 399, 'Zbook 17': 400, 'N23 (N3060/4GB/128GB/W10)': 401, 'X550VX-XX015D (i5-6300HQ/4GB/1TB/GeForce': 402, 'Thinkpad T460': 403, 'Pro P2540UA-XO0192R': 404, 'Yoga 900-13ISK': 405, '15-cb003na (i5-7300HQ/8GB/1TB': 406, 'Latitude 7280': 407, 'Zenbook UX330UA-AH5Q': 408, 'TravelMate P238-M': 409, 'X751NV-TY001 (N4200/4GB/1TB/GeForce': 410, 'Tecra A40-C-1E5': 411, 'EliteBook 820': 412, 'Q524UQ-BHI7T15 (i7-7500U/12GB/2TB/GeForce': 413, 'Thinkpad P50': 414, 'Vivobook Max': 415, 'Rog G752VS-BA171T': 416, 'Tecra Z40-C-161': 417, 'IdeaPad 110-15IBR': 418, 'GS43VR 7RE': 419, 'GL62M (i5-7300HQ/8GB/1TB': 420, 'Predator G9-793': 421, 'FX502VM-DM560T (i7-7700HQ/8GB/1TB': 422, 'K146 (N3350/4GB/32GB/W10)': 423, 'Yoga 510-15IKB': 424, 'R417NA-RS01 (N3350/4GB/32GB/W10)': 425, 'Pro P2540UA-XS51': 426, 'Latitude 3180': 427, '15-ba043na (A12-9700P/8GB/2TB/W10)': 428, 'Omen 17-an012dx': 429, 'Thinkpad T470s': 430, 'Blade Stealth': 431, 'Latitude 3480': 432, 'V110-15ISK (i3-6006U/4GB/500GB/W10)': 433, 'Tecra X40-D-10Z': 434, 'GL62M 7RD': 435, 'Rog GL702VS-BA023T': 436, 'N42-20 Chromebook': 437, 'R558UA-DM966T (i5-7200U/8GB/128GB/FHD/W10)': 438, 'Rog GL702VM-GC017T': 439, 'ZenBook UX310UQ-GL026T': 440, 'Rog GL502VM-DS74': 441, 'Inspiron 5767': 442, 'ThinkPad T470p': 443, 'K556UR-DM621T (i7-7500U/8GB/256GB/GeForce': 444, 'X541NA (N4200/4GB/1TB/W10)': 445, 'Inspiron 5368': 446, 'Portege X30-D-10X': 447, 'Portï¿½gï¿½ Z30-C-188': 448, 'TMX349-G2-M-50FS (i5-7200U/8GB/256GB/FHD/W10)': 449, 'Tecra A50-D-11D': 450, 'X541NA-GO121 (N4200/4GB/1TB/Linux)': 451, 'Pavilion x360': 452, 'VivoBook L402NA': 453, 'IdeaPad 510-15ISK': 454, 'Rog GL753VD-GC082T': 455, 'Chromebook C731-C78G': 456, 'Probook 640': 457, 'Envy x360': 458, 'GS73VR Stealth': 459, 'Portege X30-D-10V': 460, 'G701VO-IH74K (i7-6820HK/32GB/2x': 461, 'Gram 15Z970': 462, 'Chromebook CB5-571-C1DZ': 463, 'Gram 14Z970': 464, 'Elitebook Folio': 465, 'IdeaPad 510-15IKB': 466, 'GE72VR 6RF': 467, 'Envy 13-AB077cl': 468, 'Tecra Z50-C-140': 469, 'Probook 650': 470, 'Tecra Z40-C-12X': 471, 'GP62M Leopard': 472, 'Omen 17-W006na': 473, 'X751SV-TY001T (N3710/4GB/1TB/GeForce': 474, 'TravelMate P259-G2': 475, 'Tecra A50-C-1ZV': 476, 'Yoga 700-11ISK': 477, 'IdeaPad Y700-15ACZ': 478, 'Insprion 5767': 479, 'ZBook Studio': 480, 'Portege Z30-C-1CW': 481, 'ProBook x360': 482, 'Chromebook C738T-C2EJ': 483, 'Portege Z30-C-16Z': 484, 'Aspire F5-573G-510L': 485, 'Portege X20W-D-10V': 486, 'Tecra A40-C-1DF': 487, 'ThinkPad T460': 488, 'Q534UX-BHI7T19 (i7-7500U/16GB/2TB': 489, '15-bs053od (i7-7500U/6GB/1TB/W10)': 490, 'Rog GL753VE-DS74': 491, 'Inspiron 7579': 492, 'Portege Z30-C-1CV': 493, 'LifeBook A556': 494, 'Tecra A40-C-1KF': 495, '15-bs005nv (i3-6006U/4GB/1TB': 496, 'V110-15IAP (N3350/4GB/128GB/No': 497, 'ThinkPad T560': 498, 'ZenBook UX310UA-FB485T': 499, 'Spectre 13-V111dx': 500, 'Aspire ES1-533': 501, 'Rog GL553VE-DS74': 502, 'Nitro 5': 503, 'ENVY -': 504, 'Portege Z30-C-16H': 505, 'Portege A30-C-1CZ': 506, 'ThinkPad P70': 507, 'Tecra Z40-C-12Z': 508, 'Inspiron 5568': 509, 'Portï¿½gï¿½ Z30-C-16K': 510, 'Spectre 13-V100nv': 511, 'Latitude E5570': 512, 'Tecra Z40-C-136': 513, 'Yoga 500-15ISK': 514, 'V142 (X5-Z8350/2GB/32GB/W10)': 515, 'Tecra A50-C-218': 516, 'Thinkpad L560': 517, 'GT72S Dominator': 518, 'IdeaPad Y900-17ISK': 519, 'Chromebook C202SA': 520, 'Noteb Pav': 521, 'Inspiron 5578': 522, '250 G5': 523, 'Aspire ES1-523': 524, 'Inspiron 7378': 525, 'GT62VR 6RD': 526, 'Rog G752VL-GC088D': 527, 'GS63VR 6RF': 528, 'ROG G701VO': 529, 'Latitude 3570': 530, 'IdeaPad 300-17ISK': 531, 'Ideapad 700-15ISK': 532, 'GT72VR Dominator': 533, 'V110-15ISK (i5-6200U/4GB/500GB/W10)': 534, 'Yoga 900S-12ISK': 535, 'Chromebook 13': 536, 'Rog GL702VM-GC354T': 537, 'Aspire F5-573G': 538, 'GS70 Stealth': 539, 'G752VY-GC162T (i7-6700HQ/16GB/1TB': 540, 'Latitude E5270': 541, 'Chromebook 15': 542, 'GE72 Apache': 543, '15-bw011nv (A6-9220/4GB/1TB/FHD/W10)': 544, 'Rog GL552VW-CN470T': 545, 'Vostro 3559': 546, 'V110-15ISK (i3-6006U/4GB/128GB/W10)': 547, 'Spectre Pro': 548, 'Portege X30-D-10K': 549, 'Rog GL752VW-T4308T': 550, 'V131 (X5-Z8350/4GB/32GB/FHD/W10)': 551, 'Omen -': 552, '15-bs078cl (i7-7500U/8GB/2TB/W10)': 553, 'ThinkPad P40': 554, 'L403NA-GA013TS (N3350/4GB/32GB/W10)': 555, 'IdeaPad 500-15ISK': 556, 'GP62M 7RDX': 557, 'V110-15ISK (i3-6006U/4GB/1TB/No': 558, '15-BA015wm (E2-7110/4GB/500GB/W10)': 559, 'B51-80 (i5-6200U/8GB/1TB/Radeon': 560, '15-bw002nv (A6-9220/4GB/256GB/Radeon': 561, 'GP72M 7REX': 562, 'ThinkPad T460s': 563, 'B51-80 (i5-6200U/8GB/1008GB/Radeon': 564, 'GS40 Phantom': 565, 'Pavilion 15-cb003nv': 566, 'IdeaPad 310-15ISK': 567, '250 G4': 568, '320-15ISK (i3-6006U/4GB/1TB/GeForce': 569, 'Stream 14-AX000nv': 570, 'PL60 7RD': 571, 'X553SA-XX021T (N3050/4GB/500GB/W10)': 572, 'V110-15ISK (i5-6200U/4GB/500GB/No': 573, 'UX410UA-GV097T (i3-7100U/4GB/256GB/FHD/W10)': 574, 'B51-80 (i7-6500U/4GB/1008GB/FHD/W7)': 575, 'GS60 Ghost': 576, 'Pavilion 15-BC000nv': 577, 'Rog GL552VW-DM201T': 578, 'Chromebook Plus': 579, 'Pavilion Power': 580, 'V110-15ISK (i3-6006U/4GB/1TB/Radeon': 581, 'Rog G752VY-GC229T': 582, 'GS73VR 7RF': 583, 'FX502VM-DM105T (i7-6700HQ/8GB/1TB/GeForce': 584, '15-bs025nv (i5-7200U/8GB/256GB/W10)': 585, 'Aspire E5-774G': 586, 'FX502VM-AS73 (i7-7700HQ/16GB/1TB': 587, 'C740-C9QX (3205U/2GB/32GB/Chrome': 588, 'E5 774G': 589, 'SP714-51 (i7-7Y75/8GB/256GB/FHD/W10)': 590, 'Thinkpad T560': 591, 'GP62MVR 6RF': 592, '15-bw009nv (A12-9720P/6GB/1TB/Radeon': 593, 'Latitude E7270': 594, 'X540SA-RBPDN09 (N3710/4GB/1TB/W10)': 595, 'GL62M 7RDX': 596, 'GE72VR Apache': 597, '15-bs023nv (i3-6006U/4GB/1TB/FHD/W10)': 598, 'GL62 6QF': 599, 'ZenBook UX310UA-WB71': 600, 'Inspiron 7779': 601, 'Rog GL553VE-FY052T': 602, 'Rog GL502VS': 603, 'V510-15IKB (i5-7200U/8GB/256GB/FHD/No': 604, 'ThinkPad L460': 605, 'X541NA-GO020T (N3350/4GB/1TB/W10)': 606, 'Rog G752VT-GC073T': 607, 'B51-80 (i7-6500U/8GB/1008GB/Radeon': 608, 'GE62 Apache': 609, 'Yoga 500-14IBD': 610, 'ZenBook UX305CA-UBM1': 611, 'Aspire ES1-531': 612, 'Pavilion 15-AW003nv': 613, 'Stream 11-Y000na': 614, 'X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce': 615, 'Yoga 500-14ISK': 616, '15-AC110nv (i7-6500U/6GB/1TB/Radeon': 617, 'X553SA-XX031T (N3050/4GB/500GB/W10)': 618}

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\2870238369.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product'] = df['Product'].map(Product_dict)

In [ ]:
TypeName_dict={
    'Ultrabook':1,           'Notebook':2,            'Netbook':3,
             'Gaming':4, '2 in 1 Convertible':5,        'Workstation':6
}
df['TypeName'] = df['TypeName'].map(TypeName_dict)

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\390325502.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TypeName'] = df['TypeName'].map(TypeName_dict)

In [ ]:
ScreenResolution_list = df['ScreenResolution'].unique().tolist()
ScreenResolution_dict = {ScreenResolution: i+1 for i, ScreenResolution in enumerate(ScreenResolution_list)}
print(ScreenResolution_dict)
df['ScreenResolution'] = df['ScreenResolution'].map(ScreenResolution_dict)

{'IPS Panel Retina Display 2560x1600': 1, '1440x900': 2, 'Full HD 1920x1080': 3, 'IPS Panel Retina Display 2880x1800': 4, '1366x768': 5, 'IPS Panel Full HD 1920x1080': 6, 'IPS Panel Retina Display 2304x1440': 7, 'IPS Panel Full HD / Touchscreen 1920x1080': 8, 'Full HD / Touchscreen 1920x1080': 9, 'Touchscreen / Quad HD+ 3200x1800': 10, 'IPS Panel Touchscreen 1920x1200': 11, 'Touchscreen 2256x1504': 12, 'Quad HD+ / Touchscreen 3200x1800': 13, 'IPS Panel 1366x768': 14, 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160': 15, 'IPS Panel Full HD 2160x1440': 16, '4K Ultra HD / Touchscreen 3840x2160': 17, 'Touchscreen 2560x1440': 18, '1600x900': 19, 'IPS Panel 4K Ultra HD 3840x2160': 20, '4K Ultra HD 3840x2160': 21, 'Touchscreen 1366x768': 22, 'IPS Panel Full HD 1366x768': 23, 'IPS Panel 2560x1440': 24, 'IPS Panel Full HD 2560x1440': 25, 'IPS Panel Retina Display 2736x1824': 26, 'Touchscreen 2400x1600': 27, '2560x1440': 28, 'IPS Panel Quad HD+ 2560x1440': 29, 'IPS Panel Quad HD+ 3200x1800': 30, 'IPS Panel Quad HD+ / Touchscreen 3200x1800': 31, 'IPS Panel Touchscreen 1366x768': 32, '1920x1080': 33, 'IPS Panel Full HD 1920x1200': 34, 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160': 35, 'IPS Panel Touchscreen 2560x1440': 36, 'Touchscreen / Full HD 1920x1080': 37, 'Quad HD+ 3200x1800': 38, 'Touchscreen / 4K Ultra HD 3840x2160': 39, 'IPS Panel Touchscreen 2400x1600': 40}

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\4175504428.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ScreenResolution'] = df['ScreenResolution'].map(ScreenResolution_dict)

In [ ]:
Cpu_list = df['Cpu'].unique().tolist()
Cpu_dict = {Cpu: i+1 for i, Cpu in enumerate(Cpu_list)}
print(Cpu_dict)

df['Cpu'] = df['Cpu'].map(Cpu_dict)

{'Intel Core i5 2.3GHz': 1, 'Intel Core i5 1.8GHz': 2, 'Intel Core i5 7200U 2.5GHz': 3, 'Intel Core i7 2.7GHz': 4, 'Intel Core i5 3.1GHz': 5, 'AMD A9-Series 9420 3GHz': 6, 'Intel Core i7 2.2GHz': 7, 'Intel Core i7 8550U 1.8GHz': 8, 'Intel Core i5 8250U 1.6GHz': 9, 'Intel Core i3 6006U 2GHz': 10, 'Intel Core i7 2.8GHz': 11, 'Intel Core M m3 1.2GHz': 12, 'Intel Core i7 7500U 2.7GHz': 13, 'Intel Core i7 2.9GHz': 14, 'Intel Core i3 7100U 2.4GHz': 15, 'Intel Atom x5-Z8350 1.44GHz': 16, 'Intel Core i5 7300HQ 2.5GHz': 17, 'AMD E-Series E2-9000e 1.5GHz': 18, 'Intel Core i5 1.6GHz': 19, 'Intel Core i7 8650U 1.9GHz': 20, 'Intel Atom x5-Z8300 1.44GHz': 21, 'AMD E-Series E2-6110 1.5GHz': 22, 'AMD A6-Series 9220 2.5GHz': 23, 'Intel Celeron Dual Core N3350 1.1GHz': 24, 'Intel Core i3 7130U 2.7GHz': 25, 'Intel Core i7 7700HQ 2.8GHz': 26, 'Intel Core i5 2.0GHz': 27, 'AMD Ryzen 1700 3GHz': 28, 'Intel Pentium Quad Core N4200 1.1GHz': 29, 'Intel Atom x5-Z8550 1.44GHz': 30, 'Intel Celeron Dual Core N3060 1.6GHz': 31, 'Intel Core i5 1.3GHz': 32, 'AMD FX 9830P 3GHz': 33, 'Intel Core i7 7560U 2.4GHz': 34, 'AMD E-Series 6110 1.5GHz': 35, 'Intel Core i5 6200U 2.3GHz': 36, 'Intel Core M 6Y75 1.2GHz': 37, 'Intel Core i5 7500U 2.7GHz': 38, 'Intel Core i3 6006U 2.2GHz': 39, 'AMD A6-Series 9220 2.9GHz': 40, 'Intel Core i7 6920HQ 2.9GHz': 41, 'Intel Core i5 7Y54 1.2GHz': 42, 'Intel Core i7 7820HK 2.9GHz': 43, 'Intel Xeon E3-1505M V6 3GHz': 44, 'Intel Core i7 6500U 2.5GHz': 45, 'AMD E-Series 9000e 1.5GHz': 46, 'AMD A10-Series A10-9620P 2.5GHz': 47, 'AMD A6-Series A6-9220 2.5GHz': 48, 'Intel Core i5 2.9GHz': 49, 'Intel Core i7 6600U 2.6GHz': 50, 'Intel Core i3 6006U 2.0GHz': 51, 'Intel Celeron Dual Core 3205U 1.5GHz': 52, 'Intel Core i7 7820HQ 2.9GHz': 53, 'AMD A10-Series 9600P 2.4GHz': 54, 'Intel Core i7 7600U 2.8GHz': 55, 'AMD A8-Series 7410 2.2GHz': 56, 'Intel Celeron Dual Core 3855U 1.6GHz': 57, 'Intel Pentium Quad Core N3710 1.6GHz': 58, 'AMD A12-Series 9720P 2.7GHz': 59, 'Intel Core i5 7300U 2.6GHz': 60, 'AMD A12-Series 9720P 3.6GHz': 61, 'Intel Celeron Quad Core N3450 1.1GHz': 62, 'Intel Celeron Dual Core N3060 1.60GHz': 63, 'Intel Core i5 6440HQ 2.6GHz': 64, 'Intel Core i7 6820HQ 2.7GHz': 65, 'AMD Ryzen 1600 3.2GHz': 66, 'Intel Core i7 7Y75 1.3GHz': 67, 'Intel Core i5 7440HQ 2.8GHz': 68, 'Intel Core i7 7660U 2.5GHz': 69, 'Intel Core i7 7700HQ 2.7GHz': 70, 'Intel Core M m3-7Y30 2.2GHz': 71, 'Intel Core i5 7Y57 1.2GHz': 72, 'Intel Core i7 6700HQ 2.6GHz': 73, 'Intel Core i3 6100U 2.3GHz': 74, 'AMD A10-Series 9620P 2.5GHz': 75, 'AMD E-Series 7110 1.8GHz': 76, 'Intel Celeron Dual Core N3350 2.0GHz': 77, 'AMD A9-Series A9-9420 3GHz': 78, 'Intel Core i7 6820HK 2.7GHz': 79, 'Intel Core M 7Y30 1.0GHz': 80, 'Intel Xeon E3-1535M v6 3.1GHz': 81, 'Intel Celeron Quad Core N3160 1.6GHz': 82, 'Intel Core i5 6300U 2.4GHz': 83, 'Intel Core i3 6100U 2.1GHz': 84, 'AMD E-Series E2-9000 2.2GHz': 85, 'Intel Celeron Dual Core N3050 1.6GHz': 86, 'Intel Core M M3-6Y30 0.9GHz': 87, 'AMD A9-Series 9420 2.9GHz': 88, 'Intel Core i5 6300HQ 2.3GHz': 89, 'AMD A6-Series 7310 2GHz': 90, 'Intel Atom Z8350 1.92GHz': 91, 'Intel Xeon E3-1535M v5 2.9GHz': 92, 'Intel Core i5 6260U 1.8GHz': 93, 'Intel Pentium Dual Core N4200 1.1GHz': 94, 'Intel Celeron Quad Core N3710 1.6GHz': 95, 'Intel Core M 1.2GHz': 96, 'AMD A12-Series 9700P 2.5GHz': 97, 'Intel Core i7 7500U 2.5GHz': 98, 'Intel Pentium Dual Core 4405U 2.1GHz': 99, 'AMD A4-Series 7210 2.2GHz': 100, 'Intel Core i7 6560U 2.2GHz': 101, 'Intel Core M m7-6Y75 1.2GHz': 102, 'AMD FX 8800P 2.1GHz': 103, 'Intel Core M M7-6Y75 1.2GHz': 104, 'Intel Core i5 7200U 2.50GHz': 105, 'Intel Core i5 7200U 2.70GHz': 106, 'Intel Atom X5-Z8350 1.44GHz': 107, 'Intel Core i5 7200U 2.7GHz': 108, 'Intel Core M 1.1GHz': 109, 'Intel Pentium Dual Core 4405Y 1.5GHz': 110, 'Intel Pentium Quad Core N3700 1.6GHz': 111, 'Intel Core M 6Y54 1.1GHz': 112, 'Intel Core i7 6500U 2.50GHz': 113, 'Intel Celeron Dual Core N3350 2GHz': 114, 'Samsung Cortex A72&A53 2.0GHz': 115, 'AMD E-Series 9000 2.2GHz': 116, 'Intel Core M 6Y30 0.9GHz': 117, 'AMD A9-Series 9410 2.9GHz': 118}

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\1674588932.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cpu'] = df['Cpu'].map(Cpu_dict)

In [ ]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\793054076.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)

In [ ]:
Memory_list = df['Memory'].unique().tolist()
Memory_dict = {Memory: i+1 for i, Memory in enumerate(Memory_list)}
print(Memory_dict)
df['Memory'] = df['Memory'].map(Memory_dict)

{'128GB SSD': 1, '128GB Flash Storage': 2, '256GB SSD': 3, '512GB SSD': 4, '500GB HDD': 5, '256GB Flash Storage': 6, '1TB HDD': 7, '32GB Flash Storage': 8, '128GB SSD +  1TB HDD': 9, '256GB SSD +  256GB SSD': 10, '64GB Flash Storage': 11, '256GB SSD +  1TB HDD': 12, '256GB SSD +  2TB HDD': 13, '32GB SSD': 14, '2TB HDD': 15, '64GB SSD': 16, '1.0TB Hybrid': 17, '512GB SSD +  1TB HDD': 18, '1TB SSD': 19, '256GB SSD +  500GB HDD': 20, '128GB SSD +  2TB HDD': 21, '512GB SSD +  512GB SSD': 22, '16GB SSD': 23, '16GB Flash Storage': 24, '512GB SSD +  256GB SSD': 25, '512GB SSD +  2TB HDD': 26, '64GB Flash Storage +  1TB HDD': 27, '180GB SSD': 28, '1TB HDD +  1TB HDD': 29, '32GB HDD': 30, '1TB SSD +  1TB HDD': 31, '512GB Flash Storage': 32, '128GB HDD': 33, '240GB SSD': 34, '8GB SSD': 35, '508GB Hybrid': 36, '1.0TB HDD': 37, '512GB SSD +  1.0TB Hybrid': 38, '256GB SSD +  1.0TB Hybrid': 39}

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\4187801340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Memory'] = df['Memory'].map(Memory_dict)

In [ ]:
Gpu_list = df['Gpu'].unique().tolist()
Gpu_dict = {Gpu: i+1 for i, Gpu in enumerate(Gpu_list)}
print(Gpu_dict)

df['Gpu'] = df['Gpu'].map(Gpu_dict)

{'Intel Iris Plus Graphics 640': 1, 'Intel HD Graphics 6000': 2, 'Intel HD Graphics 620': 3, 'AMD Radeon Pro 455': 4, 'Intel Iris Plus Graphics 650': 5, 'AMD Radeon R5': 6, 'Intel Iris Pro Graphics': 7, 'Nvidia GeForce MX150': 8, 'Intel UHD Graphics 620': 9, 'Intel HD Graphics 520': 10, 'AMD Radeon Pro 555': 11, 'AMD Radeon R5 M430': 12, 'Intel HD Graphics 615': 13, 'AMD Radeon Pro 560': 14, 'Nvidia GeForce 940MX': 15, 'Intel HD Graphics 400': 16, 'Nvidia GeForce GTX 1050': 17, 'AMD Radeon R2': 18, 'AMD Radeon 530': 19, 'Nvidia GeForce 930MX': 20, 'Intel HD Graphics': 21, 'Intel HD Graphics 500': 22, 'Nvidia GeForce 930MX ': 23, 'Nvidia GeForce GTX 1060': 24, 'Nvidia GeForce 150MX': 25, 'Intel Iris Graphics 540': 26, 'AMD Radeon RX 580': 27, 'Nvidia GeForce 920MX': 28, 'AMD Radeon R4 Graphics': 29, 'AMD Radeon 520': 30, 'Nvidia GeForce GTX 1070': 31, 'Nvidia GeForce GTX 1050 Ti': 32, 'Nvidia GeForce MX130': 33, 'AMD R4 Graphics': 34, 'Nvidia GeForce GTX 940MX': 35, 'AMD Radeon RX 560': 36, 'Nvidia GeForce 920M': 37, 'AMD Radeon R7 M445': 38, 'AMD Radeon RX 550': 39, 'Nvidia GeForce GTX 1050M': 40, 'Intel HD Graphics 515': 41, 'AMD Radeon R5 M420': 42, 'Intel HD Graphics 505': 43, 'Nvidia GTX 980 SLI': 44, 'AMD R17M-M1-70': 45, 'Nvidia GeForce GTX 1080': 46, 'Nvidia Quadro M1200': 47, 'Nvidia GeForce 920MX ': 48, 'Nvidia GeForce GTX 950M': 49, 'AMD FirePro W4190M ': 50, 'Nvidia GeForce GTX 980M': 51, 'Intel Iris Graphics 550': 52, 'Nvidia GeForce 930M': 53, 'Intel HD Graphics 630': 54, 'AMD Radeon R5 430': 55, 'Nvidia GeForce GTX 940M': 56, 'Intel HD Graphics 510': 57, 'Intel HD Graphics 405': 58, 'AMD Radeon RX 540': 59, 'Nvidia GeForce GT 940MX': 60, 'AMD FirePro W5130M': 61, 'Nvidia Quadro M2200M': 62, 'AMD Radeon R4': 63, 'Nvidia Quadro M620': 64, 'AMD Radeon R7 M460': 65, 'Intel HD Graphics 530': 66, 'Nvidia GeForce GTX 965M': 67, 'Nvidia GeForce GTX1080': 68, 'Nvidia GeForce GTX1050 Ti': 69, 'Nvidia GeForce GTX 960M': 70, 'AMD Radeon R2 Graphics': 71, 'Nvidia Quadro M620M': 72, 'Nvidia GeForce GTX 970M': 73, 'Nvidia GeForce GTX 960<U+039C>': 74, 'Intel Graphics 620': 75, 'Nvidia GeForce GTX 960': 76, 'AMD Radeon R5 520': 77, 'AMD Radeon R7 M440': 78, 'AMD Radeon R7': 79, 'Nvidia Quadro M520M': 80, 'Nvidia Quadro M2200': 81, 'Nvidia Quadro M2000M': 82, 'Intel HD Graphics 540': 83, 'Nvidia Quadro M1000M': 84, 'AMD Radeon 540': 85, 'Nvidia GeForce GTX 1070M': 86, 'Nvidia GeForce GTX1060': 87, 'Intel HD Graphics 5300': 88, 'AMD Radeon R5 M420X': 89, 'AMD Radeon R7 Graphics': 90, 'Nvidia GeForce 920': 91, 'Nvidia GeForce 940M': 92, 'Nvidia GeForce GTX 930MX': 93, 'AMD Radeon R7 M465': 94, 'AMD Radeon R3': 95, 'Nvidia GeForce GTX 1050Ti': 96, 'AMD Radeon R7 M365X': 97, 'AMD Radeon R9 M385': 98, 'Intel HD Graphics 620 ': 99, 'Nvidia Quadro 3000M': 100, 'Nvidia GeForce GTX 980 ': 101, 'AMD Radeon R5 M330': 102, 'AMD FirePro W4190M': 103, 'AMD FirePro W6150M': 104, 'AMD Radeon R5 M315': 105, 'Nvidia Quadro M500M': 106, 'AMD Radeon R7 M360': 107, 'Nvidia Quadro M3000M': 108, 'Nvidia GeForce 960M': 109, 'ARM Mali T860 MP4': 110}

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\3723082143.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gpu'] = df['Gpu'].map(Gpu_dict)

In [ ]:
OpSys_list = df['OpSys'].unique().tolist()
OpSys_dict = {OpSys: i+1 for i, OpSys in enumerate(OpSys_list)}
print(OpSys_dict)
df['OpSys'] = df['OpSys'].map(OpSys_dict)

{'macOS': 1, 'No OS': 2, 'Windows 10': 3, 'Mac OS X': 4, 'Linux': 5, 'Android': 6, 'Windows 10 S': 7, 'Chrome OS': 8, 'Windows 7': 9}

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\1225046315.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['OpSys'] = df['OpSys'].map(OpSys_dict)

In [ ]:
df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_14952\1505251675.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)

In [ ]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,1,1,13.3,1,1,8,1,1,1,1.37,1339.69
1,1,2,1,13.3,2,2,8,2,2,1,1.34,898.94
2,2,3,2,15.6,3,3,8,3,3,2,1.86,575.00
3,1,1,1,15.4,4,4,16,4,4,1,1.83,2537.45
4,1,1,1,13.3,1,5,8,3,5,1,1.37,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...
1270,6,616,5,14.0,8,45,4,1,10,3,1.80,638.00
1271,6,405,5,13.3,31,45,16,4,10,3,1.30,1499.00
1272,6,343,2,14.0,5,86,2,11,21,3,1.50,229.00
1273,2,617,2,15.6,5,45,6,7,102,3,2.19,764.00
1274,4,618,2,15.6,5,86,4,5,21,3,2.20,369.00

In [ ]:
# df.to_csv('laptop_price_cleaned.csv')

In [ ]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,1,1,13.3,1,1,8,1,1,1,1.37,1339.69
1,1,2,1,13.3,2,2,8,2,2,1,1.34,898.94
2,2,3,2,15.6,3,3,8,3,3,2,1.86,575.00
3,1,1,1,15.4,4,4,16,4,4,1,1.83,2537.45
4,1,1,1,13.3,1,5,8,3,5,1,1.37,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...
1270,6,616,5,14.0,8,45,4,1,10,3,1.80,638.00
1271,6,405,5,13.3,31,45,16,4,10,3,1.30,1499.00
1272,6,343,2,14.0,5,86,2,11,21,3,1.50,229.00
1273,2,617,2,15.6,5,45,6,7,102,3,2.19,764.00
1274,4,618,2,15.6,5,86,4,5,21,3,2.20,369.00

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [ ]:
x=df.drop(['Price_euros'],axis=1)

In [ ]:
y= df[['Price_euros']]

In [ ]:
x

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,1,1,1,13.3,1,1,8,1,1,1,1.37
1,1,2,1,13.3,2,2,8,2,2,1,1.34
2,2,3,2,15.6,3,3,8,3,3,2,1.86
3,1,1,1,15.4,4,4,16,4,4,1,1.83
4,1,1,1,13.3,1,5,8,3,5,1,1.37
...,...,...,...,...,...,...,...,...,...,...,...
1270,6,616,5,14.0,8,45,4,1,10,3,1.80
1271,6,405,5,13.3,31,45,16,4,10,3,1.30
1272,6,343,2,14.0,5,86,2,11,21,3,1.50
1273,2,617,2,15.6,5,45,6,7,102,3,2.19
1274,4,618,2,15.6,5,86,4,5,21,3,2.20

In [ ]:
y

      Price_euros
0         1339.69
1          898.94
2          575.00
3         2537.45
4         1803.60
...           ...
1270       638.00
1271      1499.00
1272       229.00
1273       764.00
1274       369.00

[1275 rows x 1 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=42)

In [ ]:
x_train

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
413,3,140,5,13.3,8,45,8,3,10,3,1.60
778,14,121,4,14.0,3,26,16,4,24,3,1.95
1107,6,514,5,15.6,8,36,4,3,10,3,2.10
96,5,7,2,15.6,3,13,8,7,12,5,2.20
309,2,3,2,15.6,3,10,4,7,10,3,1.86
...,...,...,...,...,...,...,...,...,...,...,...
1044,2,101,2,14.0,3,36,4,5,10,3,1.54
1095,3,538,2,15.6,3,3,8,12,49,3,2.40
1130,2,553,2,15.6,5,13,8,15,3,3,2.04
860,6,264,2,15.6,6,3,8,7,3,3,2.30
1126,6,34,5,10.1,11,30,4,11,16,3,0.69

In [ ]:
x_test

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
1179,2,25,2,15.6,5,74,4,5,10,3,2.07
342,2,25,2,15.6,6,15,8,7,23,3,2.10
649,6,265,1,12.5,6,13,8,3,3,3,1.36
772,10,411,2,14.0,14,36,4,1,10,3,1.75
803,5,116,2,15.6,17,17,8,3,17,3,2.06
...,...,...,...,...,...,...,...,...,...,...,...
701,6,56,2,15.6,3,88,4,3,19,3,2.20
1105,5,541,1,12.5,5,36,8,3,10,9,1.50
424,5,133,4,17.3,24,43,16,12,31,3,4.42
944,6,477,5,11.3,8,102,8,3,41,3,1.10
65,4,44,1,15.6,3,26,16,4,32,3,1.80

In [ ]:
y_train

      Price_euros
413        789.01
778       2899.00
1107       867.00
96         599.90
309        469.00
...           ...
1044      1000.00
1095       799.00
1130       629.00
860        850.66
1126       479.00

[1020 rows x 1 columns]

In [ ]:
y_test

      Price_euros
1179        650.0
342         716.0
649        1584.0
772        1020.0
803        1749.0
...           ...
701         399.0
1105       1413.1
424        2799.0
944        1299.0
65         1983.0

[255 rows x 1 columns]

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1020, 11), (255, 11), (1020, 1), (255, 1))

# Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
pred=lr.predict(x_test)
print(pred)
print("LinearRegression tain score:-",lr.score(x_train,y_train))
print("LinearRegression test score:-",lr.score(x_test,y_test))

[[ 623.90315705]
 [ 990.23444813]
 [1119.5555337 ]
 [ 810.07895727]
 [1115.91449296]
 [1016.62285812]
 [1535.13507882]
 [ 614.66072141]
 [1886.06887098]
 [ 621.41340572]
 [1529.149235  ]
 [1087.03360955]
 [1178.10531162]
 [ 955.38378102]
 [2287.98710167]
 [ 871.98791911]
 [1048.68107186]
 [1094.56487508]
 [1280.99463795]
 [2112.5477003 ]
 [ 808.54742453]
 [ 700.40332113]
 [1335.01952334]
 [2126.46289345]
 [ 781.18473511]
 [1832.22573034]
 [ 677.69244258]
 [1142.20812704]
 [ 793.2410153 ]
 [1032.74066786]
 [1289.46050818]
 [ 596.51739878]
 [1036.63904942]
 [ 585.71554509]
 [1407.16970676]
 [1326.50961036]
 [1108.1513087 ]
 [ 566.49072834]
 [1058.38001644]
 [1254.43795448]
 [1669.07478586]
 [ 617.45454768]
 [1318.72986086]
 [1074.90563578]
 [1031.10544609]
 [1167.10267407]
 [1158.86340495]
 [ 715.77069293]
 [1860.23590884]
 [1232.03395988]
 [1153.37311848]
 [ 445.11489664]
 [2173.73386908]
 [ 614.87255678]
 [ 974.52441728]
 [1312.66035984]
 [ 665.75372238]
 [1055.91344621]
 [1093.8407572 ]
 [1056.98579127]
 [ 613.54240129]
 [1083.31087278]
 [1895.53050162]
 [ 592.8606369 ]
 [ 744.02160957]
 [ 515.20677961]
 [1054.74044836]
 [1137.64947957]
 [ 533.0016266 ]
 [ 614.56380851]
 [1066.4676751 ]
 [ 961.82734681]
 [1149.32636017]
 [1810.8365101 ]
 [1065.88649034]
 [ 652.51223378]
 [1858.94392048]
 [1316.53993109]
 [ 903.12003365]
 [ 573.75734449]
 [2297.81454932]
 [1326.05780231]
 [ 658.12361189]
 [1053.22534391]
 [ 706.34785962]
 [1812.59206909]
 [ 847.3429495 ]
 [1720.78716981]
 [1962.44527179]
 [1289.04208614]
 [1738.64366953]
 [ 621.86043834]
 [ 514.36804698]
 [1085.15066067]
 [1371.91649451]
 [1065.23900554]
 [ 969.64484059]
 [ 902.39082168]
 [1323.3985547 ]
 [1094.89783688]
 [3378.51157399]
 [ 987.22662469]
 [1895.49832798]
 [ 718.17716984]
 [1121.18999639]
 [1026.5566309 ]
 [ 789.1520387 ]
 [1098.67245905]
 [1754.09387556]
 [1226.05550069]
 [ 589.33533853]
 [1414.47625274]
 [1031.66537364]
 [ 957.25764222]
 [3489.42890662]
 [ 589.47990093]
 [2104.57202117]
 [1109.83873546]
 [ 550.45674763]
 [ 643.91259417]
 [1124.82782059]
 [2012.97288496]
 [ 948.60951106]
 [1084.86034228]
 [1100.73310383]
 [1042.58346328]
 [1065.84105505]
 [1391.17236178]
 [ 903.1326484 ]
 [1013.72368217]
 [ 844.96546774]
 [ 433.90781015]
 [ 636.40284812]
 [1347.02236729]
 [1925.59826628]
 [ 866.4624667 ]
 [1516.32698315]
 [ 975.63966059]
 [1103.71421744]
 [1374.57651157]
 [1063.43178268]
 [1056.45913255]
 [1901.48443597]
 [ 875.33251677]
 [1347.44957943]
 [ 717.26856309]
 [1889.96576098]
 [ 992.69593584]
 [1025.65171222]
 [ 949.28720161]
 [1049.45254534]
 [ 987.39716135]
 [1161.11214824]
 [ 989.16206019]
 [ 972.81509808]
 [1249.95337619]
 [1944.50181017]
 [2122.22484528]
 [ 768.61143202]
 [ 919.95421916]
 [ 578.47564262]
 [2061.4011747 ]
 [1018.12536703]
 [ 958.00172175]
 [ 941.84122832]
 [ 767.55955221]
 [1801.29525521]
 [2015.25312422]
 [ 641.66956077]
 [ 603.67334148]
 [1056.27642205]
 [ 575.39448153]
 [ 986.18200714]
 [1059.47760937]
 [ 624.93497495]
 [1752.92287759]
 [1113.88306512]
 [1049.72284137]
 [1049.49158925]
 [1899.29922477]
 [1035.12892061]
 [1320.84028767]
 [2054.83297237]
 [1030.97660212]
 [2320.8423982 ]
 [1082.36514515]
 [1495.36538207]
 [1005.36467458]
 [ 881.53873237]
 [2647.22650047]
 [1127.77542942]
 [1103.0056593 ]
 [ 583.36571024]
 [1104.33259959]
 [ 658.2979708 ]
 [ 638.31930755]
 [ 652.57698852]
 [1898.98311525]
 [3436.57444388]
 [1032.60824606]
 [1175.1912522 ]
 [ 791.27653034]
 [1353.5525916 ]
 [1083.12267231]
 [1177.69811932]
 [1875.9965963 ]
 [1108.39887201]
 [ 999.1533255 ]
 [ 863.51400345]
 [ 846.28246427]
 [1120.4290304 ]
 [1090.32256902]
 [1084.24364714]
 [ 943.98051243]
 [1158.13485704]
 [1882.76670043]
 [1088.32086961]
 [ 504.59489068]
 [ 562.03608264]
 [ 578.15884667]
 [1451.99818214]
 [1310.32506975]
 [1828.94151186]
 [1055.91344621]
 [ 949.11460822]
 [1976.59772694]
 [3239.03599938]
 [ 687.90661666]
 [1169.04463096]
 [1399.55363049]
 [ 955.34809735]
 [1040.71748152]
 [1036.03604951]
 [1318.05177895]
 [1384.75113807]
 [1015.40237564]
 [1077.12959831]
 [ 968.21455199]
 [ 625.64159377]
 [3554.40820537]
 [1833.81768944]
 [1114.58346767]
 [1810.4173792 ]
 [1364.19371556]
 [1060.71067446]
 [1253.34719322]
 [ 511.7481677 ]
 [1235.19503319]
 [1024.2233685 ]
 [1343.92322583]
 [ 647.28479398]
 [1337.35632501]
 [1917.47967479]
 [1460.81138955]
 [1776.42551284]]
LinearRegression tain score:- 0.5748091976504595
LinearRegression test score:- 0.6160425771533364

In [ ]:
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,1,1,13.3,1,1,8,1,1,1,1.37,1339.69
1,1,2,1,13.3,2,2,8,2,2,1,1.34,898.94
2,2,3,2,15.6,3,3,8,3,3,2,1.86,575.00
3,1,1,1,15.4,4,4,16,4,4,1,1.83,2537.45
4,1,1,1,13.3,1,5,8,3,5,1,1.37,1803.60

# SVM (SVR)

In [ ]:
from sklearn.svm import SVR
sv=SVR()
sv.fit(x_train,y_train)

c:\Users\KRISHAN\Downloads\data science\projects\laptop price prediction\laptop_venv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [ ]:
pred=sv.predict(x_test)
print(pred)
print('SVR test score:-',sv.score(x_test,y_test))
print('SVR train score:-',sv.score(x_train,y_train))

[ 964.45053019  961.34457074  991.85945254  998.68485275  972.7823709
  959.69193506  961.79561738  977.27873668  998.25401344  961.2003816
  995.80170787  962.71443302  994.86369029  961.45518323  981.40389958
  963.61531708  960.6760028   998.34784789  965.87075858  994.15537866
  970.17158936 1000.2930001   966.71495635  998.66869225  997.00708768
 1000.5452757   963.60425455  997.87012307 1000.61177869  979.35178295
  970.26163889  958.86336801  971.96152222  965.77407891  968.01167686
  960.12663445  968.46066825  964.75442614  994.1610038   994.2058554
  961.26916351  995.15870981  991.96190987  996.82833856  961.31576709
  990.98575539  994.97659329  961.9911515  1000.82037941  970.58308837
  976.5725814   984.57329359  983.59432386  987.30141937  958.99701929
  998.75126989  980.8596842   959.67023998  962.18117721  977.49991626
  995.57151023  962.14380609  996.36520548  987.81519081  996.26298667
  961.20211987  961.57792213  969.85301121  995.3869841   958.9227092
  998.34620198  970.78300777  992.24073464  974.40159173  960.31373258
  977.97658262  995.69394689  965.05485959  965.22427341  997.94482437
 1000.23306706  960.08622687  995.31687268  994.45374231  959.54447931
  963.71248575  986.23847151  991.78608044  998.65860348  995.55818681
  960.66313534  995.84127937  962.66651879  982.32697466  995.22654104
  971.65212029  964.47803     960.65520588  997.17212222  994.06895143
  977.0380116   994.07775249  995.51723042  960.51448079  991.2771106
  991.49127346  959.70983521  989.92710175  967.77373845  998.76675215
  981.20727309  989.74188617  992.56653433  959.45280097  976.65760027
  982.52028477  979.41175512  999.10774495  965.47894521  963.92065073
  991.5513981   997.96453011  959.83300032  980.79281042  960.78031673
  977.98923186  992.57354355  989.66271052  960.48535012  997.95118802
  960.42620782  961.04471279  969.88230311  996.88038549  998.16359989
  962.96606056  991.88610983  962.16747974  994.01209774  995.58210662
  989.21272628  996.06807583  998.11344862  962.10487337 1000.20019266
  966.58333549  995.26750269  964.90658741 1000.56264523  972.54004002
  966.21395047  968.17226809  994.74222851  997.72084764  996.1614747
  997.53590542  997.98394497  994.1519289   996.66186233  989.94426993
  961.39902261  999.84302447  994.59687283  959.3541637   960.46112312
  996.024138    995.6112786   983.06120612  986.08527482  989.90287349
  989.01883572  959.41453111  961.51780573  997.69053137  961.96401424
  998.09672367  966.41367095  974.67294282  993.85293038  982.73398468
  963.55457235  993.15871682  970.91591855  974.21641274  999.50174485
  983.6696228   993.03963001  969.0549502   963.68523318  996.6925491
  990.98377324  990.94174103  959.11672109  986.11994172  981.20758539
  997.47892806  989.75197875  971.07098893  977.00378053  996.8366826
  971.06969571  982.89108266  989.79029987  968.1188906   997.67823371
  996.61264923  986.63874309  982.64719416  982.84139245  966.1236608
  991.21325728  975.00407211  996.57535758  967.39698987  989.90420538
  979.53833694  995.78738865  995.84509842  958.86381533  969.69276598
  995.36028263  997.39172629  976.10777748  959.67023998  992.91730536
  961.15104586  977.94697741  996.59304691  998.1047789   959.46870901
  987.68670969  992.80679537  987.45746581  976.67070649  990.36480732
  978.01643264  966.51680424  966.54211481  998.60371935 1001.39069779
  995.46433287  997.55900389  986.98487018  988.76783522  968.27816225
  970.5317676   965.50295331  979.24260004  966.86457086  997.18118026
  968.6605479   992.55909213  977.48227272  998.1849715   964.17132972]
SVR test score:- -0.06811897969949321
SVR train score:- -0.03844846443905725

# DecisionTreeRegressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt =DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [ ]:
# pred=dt.predict(x_test)
# print(pred)
print('DecisionTreeRegressor test score:-',dt.score(x_test,y_test))
print('DecisionTreeRegressor train score:-',dt.score(x_train,y_train))

DecisionTreeRegressor test score:- 0.7310876140710023
DecisionTreeRegressor train score:- 0.9996512079646255

## with perameter

In [ ]:
print(dt.get_params())
from sklearn.tree import DecisionTreeRegressor
# import joblib
dt = DecisionTreeRegressor(criterion='squared_error',min_samples_split=3,splitter= 'best',min_samples_leaf=2,random_state=42)
dt.fit(x_train, y_train)

{'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'random_state': None, 'splitter': 'best'}

DecisionTreeRegressor(min_samples_leaf=2, min_samples_split=3, random_state=42)

In [ ]:
# joblib.dump(dt, 'DecisionTreeRegressor_model.lb')
# print("Model saved successfully!")

# model=joblib.load('DecisionTreeRegressor_model.lb')
# print(model.predict(x_test))

In [ ]:
pred=dt.predict(x_test)
print(pred)
print("DecisionTreeRegressor Test Score:", dt.score(x_test, y_test))
print("DecisionTreeRegressor Train Score:", dt.score(x_train, y_train))

[ 921.          860.5        1609.66666667  633.5        1198.
  569.47        519.66333333  342.66666667 2372.          448.
  509.63333333 1560.33333333  994.33333333 1609.66666667 2372.46333333
  844.         1281.2        1449.         1756.245      2639.66666667
  484.          374.         1500.         1766.5         484.
 2465.66666667  754.33333333  728.505       337.66333333  827.66666667
  862.          543.845       536.          342.66666667  666.33333333
  720.33333333  862.          323.50333333  870.975      1326.
 1206.66666667  732.16       1202.         1326.         1326.
  994.         1549.          754.33333333 2465.66666667  795.45
  808.          242.33333333 1665.          215.45        632.5
 1792.5        1090.995      1424.45       1373.5         793.
  952.5         798.705      1245.98333333  516.48666667 1042.
  313.995       798.705       905.33333333  242.33333333  618.95
 1111.5         795.45       1765.5        1478.          994.
  581.53333333 1545.9         862.         1281.2         470.675
 2639.66666667  720.33333333  719.         1198.          718.33333333
 2222.          539.         1111.         2099.          562.33333333
 1092.          269.5         323.50333333 1436.          819.
  832.         1165.7         912.         1090.33333333 1014.445
 2746.          656.17        924.5        1195.         1097.72
 1199.          428.82       1135.355      1605.33333333 1792.5
  333.5        1183.33333333  793.          552.         4762.66666667
  452.45       2089.80666667 1792.5         608.95        737.745
 1202.         2089.80666667  822.          919.         1098.5
  827.66666667  821.         1475.66666667  912.          962.31
 1042.          242.33333333  524.5        1549.         1599.
 1039.5        1234.          519.66333333  632.33333333 1410.6
 1829.          994.33333333 1414.          844.         1792.5
  685.66666667 2099.         1282.16       1234.         1884.5
 1094.33333333  687.26333333 1630.          933.          933.
 1278.         2338.         2639.66666667  583.66666667  374.
  359.         1721.          509.63333333  857.66666667 1035.66666667
 1195.          989.005      2639.66666667  301.5         448.
  666.33333333  428.82        519.66333333 1630.          737.745
 2465.66666667 1194.5         671.33333333 1326.         2345.25
  793.         1079.         1245.98333333  862.         1721.
  827.66666667 1300.33333333  409.          844.         2716.33333333
 1788.605      1234.          543.845      1110.83333333  333.5
  719.          541.5        1583.         2746.          276.
 1406.          333.5        1094.33333333  905.33333333  933.
 1799.         1449.         1253.          342.66666667  814.975
 1202.         1135.355      1198.         1035.66666667  933.
 1583.         1202.          470.675       543.845       301.5
 1844.5        1231.33333333 2722.70333333 1424.45       1253.
 1169.         4762.66666667  374.         1113.37        569.47
  633.5        1691.66666667 1094.33333333 1474.         1379.
  893.95       1057.5        1261.5         186.5        1971.
 1545.9        1110.83333333 1969.95       2271.5        1326.
 1090.33333333  925.         1449.          827.66666667 1090.33333333
  372.33333333 1788.605      2926.99666667 1475.66666667 1324.        ]
DecisionTreeRegressor Test Score: 0.7719448031191424
DecisionTreeRegressor Train Score: 0.9695469232361134

## RandomForestRegressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor 
import joblib
rfr =RandomForestRegressor()
rfr.fit(x_train, y_train)

c:\Users\KRISHAN\Downloads\data science\projects\laptop price prediction\laptop_venv\lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [ ]:
print(' test score:-',rfr.score(x_test,y_test))
print('train score:-',rfr.score(x_train,y_train))

 test score:- 0.8374483220912412
train score:- 0.9692439640591111

In [ ]:
joblib.dump(rfr, 'RandomForestRegressor.lb')
print("Model saved successfully!")

model=joblib.load('RandomForestRegressor.lb')
print(model.predict(x_test))

Model saved successfully!
[ 678.0598      868.7275     1611.6012      669.3101      885.5243
  677.9961      942.2206      338.0971     2230.892       560.467
  777.9167     1324.71846667 1092.0425     1654.7577     2144.87323333
  753.7483     1428.119      1049.9885     1610.441      2215.3662
  502.4682      382.12895    1642.1027     1927.535       716.5368
 2459.9458      781.7392      849.6301      481.0682      907.71028333
 1025.7722      556.5934      809.5311      326.2354      721.2546
  787.62696667 1020.9681      431.2305     1187.502      1016.5344
 1300.9245      500.4927     1189.5703     1083.0846      883.93608333
 1267.184      1550.1278      879.29846667 2286.63        959.044
  921.8508      250.7929     1700.157       248.0059      651.4825
 1560.665      1119.6478     1483.1335     1247.9006      771.8395
  941.8196      735.26487333 1811.3951      602.7658      939.2328
  457.0092      695.7759      964.60688333  248.7736      573.157
 1255.9879      969.5459     1729.00666667 1585.6241      940.49
  545.1438     1786.13        885.6629     1709.918       475.7153
 2802.9166      835.4104      672.6869     1125.2946      651.01833333
 2130.856       540.8219     1896.123      1731.8286      729.0538
 1165.2116      265.7215      475.6411     1449.8782      882.527
 1317.5433     1046.3953     1025.0398     1035.4501      981.8948
 3021.8588      986.8279     2265.2613     1408.1045     1167.6823
 1101.4798      445.5065     1032.8455     1525.8305     1528.814
  390.9439     1023.1663      874.7081      753.76       4465.8551
  529.6424     2226.2635781  1561.0507      614.067       576.1845
 1185.0675     2277.48755333  625.2688      958.8269     1157.1447
  816.36875     869.1848     1491.0689      949.2989      923.9618
  986.8673      247.0932      570.7757     1540.3457     1873.82856667
 1147.4835     1548.9793      676.6617      604.006      1676.911
 1811.1649      820.2897     1587.6251      773.5633     1680.936
  687.59466667 1619.1676     1256.2466      964.6373     1717.8466
 1293.92083333  730.9865     1659.81343333  953.0861      792.4226
 1321.5315     2094.387      2228.2289      769.6592      374.73032
  406.618      2263.8916      629.526       746.2756      972.74115
 1225.105      1690.7193     2484.0988      327.5091      507.9308
  807.6878      428.4606      759.6363     1626.3892      559.4111
 2507.3541     1018.0793      888.8861     1211.6667     2086.7288
  713.57351667 1540.512      1373.82443333 1015.05       2008.5374
  962.5176     1296.4554      706.5117      791.84786667 2333.2092
 1617.9559     1253.855       614.9474     1214.628       386.7141
  627.5893      679.3329     1429.074      2787.6629      350.77651905
 1420.3945      543.2976     1585.91506667  870.0848      937.0272
 1652.94126667 1243.3149     1063.9419      376.618       951.6938
 1171.1371     1047.6128     1071.5261     1001.17        944.34785
 1794.3385     1378.9773      496.3271      512.9258      293.4474
 1189.687      1157.6315     2511.272      1483.1335     1055.0414
 1234.6841     3644.1489      348.4189     1063.2001      595.8229
  690.0228     1753.8888     1908.09       1533.6576     1293.2851
  845.01373333 1021.3689     1140.1102      259.4867     2772.3867
 1833.0918     1120.5258     1750.8052     2132.392       960.4439
 1029.7899      604.9914     1235.2804      911.64665    1041.8038
  409.0181     1565.7694     2825.955      1277.8004     1597.8175    ]

## with parameter

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(criterion='squared_error', min_samples_split=3, min_samples_leaf=2, random_state=42)
rfr.fit(x_train, y_train)

c:\Users\KRISHAN\Downloads\data science\projects\laptop price prediction\laptop_venv\lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(min_samples_leaf=2, min_samples_split=3, random_state=42)

In [ ]:
print(' test score:-',rfr.score(x_test,y_test))
print('train score:-',rfr.score(x_train,y_train))

 test score:- 0.8226786184484616
train score:- 0.946186877345272